import type { CoinDefinition } from './types';

export const coins: CoinDefinition[] = [
  // ── Layer 1 Blockchains ──
  { id: 'btc', name: 'Bitcoin', symbol: 'BTC', generator: 'btc-segwit', params: { hrp: 'bc' }, category: 'Layer 1', color: '#F7931A' },
  { id: 'eth', name: 'Ethereum', symbol: 'ETH', generator: 'evm', params: {}, category: 'Layer 1', color: '#627EEA' },
  { id: 'sol', name: 'Solana', symbol: 'SOL', generator: 'solana', params: {}, category: 'Layer 1', color: '#9945FF' },
  { id: 'xrp', name: 'XRP', symbol: 'XRP', generator: 'xrp', params: {}, category: 'Layer 1', color: '#23292F' },
  { id: 'ada', name: 'Cardano', symbol: 'ADA', generator: 'cardano', params: {}, category: 'Layer 1', color: '#0033AD' },
  { id: 'trx', name: 'Tron', symbol: 'TRX', generator: 'tron', params: {}, category: 'Layer 1', color: '#FF0013' },
  { id: 'avax', name: 'Avalanche', symbol: 'AVAX', generator: 'evm', params: {}, category: 'Layer 1', color: '#E84142' },
  { id: 'dot', name: 'Polkadot', symbol: 'DOT', generator: 'polkadot', params: { networkId: 0 }, category: 'Layer 1', color: '#E6007A' },
  { id: 'ton', name: 'Toncoin', symbol: 'TON', generator: 'ton', params: {}, category: 'Layer 1', color: '#0098EA' },
  { id: 'near', name: 'NEAR Protocol', symbol: 'NEAR', generator: 'near', params: {}, category: 'Layer 1', color: '#00C08B' },
  { id: 'apt', name: 'Aptos', symbol: 'APT', generator: 'aptos', params: {}, category: 'Layer 1', color: '#4DC9B0' },
  { id: 'sui', name: 'Sui', symbol: 'SUI', generator: 'sui', params: {}, category: 'Layer 1', color: '#4DA2FF' },
  { id: 'algo', name: 'Algorand', symbol: 'ALGO', generator: 'algorand', params: {}, category: 'Layer 1', color: '#000000' },
  { id: 'xtz', name: 'Tezos', symbol: 'XTZ', generator: 'tezos', params: {}, category: 'Layer 1', color: '#2C7DF7' },
  { id: 'fil', name: 'Filecoin', symbol: 'FIL', generator: 'filecoin', params: {}, category: 'Layer 1', color: '#0090FF' },
  { id: 'xlm', name: 'Stellar', symbol: 'XLM', generator: 'stellar', params: {}, category: 'Layer 1', color: '#14B6E7' },
  { id: 'hbar', name: 'Hedera', symbol: 'HBAR', generator: 'hedera', params: {}, category: 'Layer 1', color: '#3A3A3A' },
  { id: 'xmr', name: 'Monero', symbol: 'XMR', generator: 'monero', params: {}, category: 'Layer 1', color: '#FF6600' },
  { id: 'eos', name: 'EOS', symbol: 'EOS', generator: 'eos', params: {}, category: 'Layer 1', color: '#443F54' },
  { id: 'ksm', name: 'Kusama', symbol: 'KSM', generator: 'polkadot', params: { networkId: 2 }, category: 'Layer 1', color: '#E6007A' },

  // ── Bitcoin Forks ──
  { id: 'ltc', name: 'Litecoin', symbol: 'LTC', generator: 'btc-legacy', params: { versionByte: 0x30, wifByte: 0xb0 }, category: 'Bitcoin Fork', color: '#BFBBBB' },
  { id: 'doge', name: 'Dogecoin', symbol: 'DOGE', generator: 'btc-legacy', params: { versionByte: 0x1e, wifByte: 0x9e }, category: 'Bitcoin Fork', color: '#C2A633' },
  { id: 'bch', name: 'Bitcoin Cash', symbol: 'BCH', generator: 'btc-legacy', params: { versionByte: 0x00, wifByte: 0x80 }, category: 'Bitcoin Fork', color: '#0AC18E' },
  { id: 'dash', name: 'Dash', symbol: 'DASH', generator: 'btc-legacy', params: { versionByte: 0x4c, wifByte: 0xcc }, category: 'Bitcoin Fork', color: '#008CE7' },
  { id: 'zec', name: 'Zcash', symbol: 'ZEC', generator: 'btc-legacy', params: { versionByte: [0x1c, 0xb8], wifByte: 0x80 }, category: 'Bitcoin Fork', color: '#F4B728' },
  { id: 'dgb', name: 'DigiByte', symbol: 'DGB', generator: 'btc-legacy', params: { versionByte: 0x1e, wifByte: 0x80 }, category: 'Bitcoin Fork', color: '#006AD2' },
  { id: 'rvn', name: 'Ravencoin', symbol: 'RVN', generator: 'btc-legacy', params: { versionByte: 0x3c, wifByte: 0x80 }, category: 'Bitcoin Fork', color: '#384182' },
  { id: 'bsv', name: 'Bitcoin SV', symbol: 'BSV', generator: 'btc-legacy', params: { versionByte: 0x00, wifByte: 0x80 }, category: 'Bitcoin Fork', color: '#EAB300' },
  { id: 'dcr', name: 'Decred', symbol: 'DCR', generator: 'btc-legacy', params: { versionByte: [0x07, 0x3f], wifByte: 0x80 }, category: 'Bitcoin Fork', color: '#2ED6A1' },
  { id: 'zen', name: 'Horizen', symbol: 'ZEN', generator: 'btc-legacy', params: { versionByte: [0x20, 0x89], wifByte: 0x80 }, category: 'Bitcoin Fork', color: '#00A98D' },
  { id: 'sys', name: 'Syscoin', symbol: 'SYS', generator: 'btc-legacy', params: { versionByte: 0x3f, wifByte: 0xbf }, category: 'Bitcoin Fork', color: '#0082C6' },

  // ── EVM Chains ──
  { id: 'bnb', name: 'BNB Smart Chain', symbol: 'BNB', generator: 'evm', params: {}, category: 'EVM Chain', color: '#F0B90B', parentChain: 'EVM' },
  { id: 'pol', name: 'Polygon', symbol: 'POL', generator: 'evm', params: {}, category: 'EVM Chain', color: '#8247E5', parentChain: 'EVM' },
  { id: 'arb', name: 'Arbitrum', symbol: 'ARB', generator: 'evm', params: {}, category: 'EVM Chain', color: '#28A0F0', parentChain: 'EVM' },
  { id: 'op', name: 'Optimism', symbol: 'OP', generator: 'evm', params: {}, category: 'EVM Chain', color: '#FF0420', parentChain: 'EVM' },
  { id: 'base', name: 'Base', symbol: 'BASE', generator: 'evm', params: {}, category: 'EVM Chain', color: '#0052FF', parentChain: 'EVM' },
  { id: 'ftm', name: 'Fantom', symbol: 'FTM', generator: 'evm', params: {}, category: 'EVM Chain', color: '#1969FF', parentChain: 'EVM' },
  { id: 'cro', name: 'Cronos', symbol: 'CRO', generator: 'evm', params: {}, category: 'EVM Chain', color: '#002D74', parentChain: 'EVM' },
  { id: 'mnt', name: 'Mantle', symbol: 'MNT', generator: 'evm', params: {}, category: 'EVM Chain', color: '#000000' , parentChain: 'EVM' },
  { id: 'celo', name: 'Celo', symbol: 'CELO', generator: 'evm', params: {}, category: 'EVM Chain', color: '#FBCC5C', parentChain: 'EVM' },
  { id: 'glmr', name: 'Moonbeam', symbol: 'GLMR', generator: 'evm', params: {}, category: 'EVM Chain', color: '#53CBC9', parentChain: 'EVM' },
  { id: 'metis', name: 'Metis', symbol: 'METIS', generator: 'evm', params: {}, category: 'EVM Chain', color: '#00DACC', parentChain: 'EVM' },
  { id: 'klay', name: 'Klaytn', symbol: 'KLAY', generator: 'evm', params: {}, category: 'EVM Chain', color: '#4F473B', parentChain: 'EVM' },
  { id: 'gno', name: 'Gnosis', symbol: 'GNO', generator: 'evm', params: {}, category: 'EVM Chain', color: '#04795B', parentChain: 'EVM' },
  { id: 'linea', name: 'Linea', symbol: 'LINEA', generator: 'evm', params: {}, category: 'EVM Chain', color: '#121212', parentChain: 'EVM' },
  { id: 'scroll', name: 'Scroll', symbol: 'SCROLL', generator: 'evm', params: {}, category: 'EVM Chain', color: '#FFEEDA', parentChain: 'EVM' },
  { id: 'zksync', name: 'zkSync Era', symbol: 'ZK', generator: 'evm', params: {}, category: 'EVM Chain', color: '#4E529A', parentChain: 'EVM' },
  { id: 'blast', name: 'Blast', symbol: 'BLAST', generator: 'evm', params: {}, category: 'EVM Chain', color: '#FCFC03', parentChain: 'EVM' },
  { id: 'flr', name: 'Flare', symbol: 'FLR', generator: 'evm', params: {}, category: 'EVM Chain', color: '#E42058', parentChain: 'EVM' },
  { id: 'vet', name: 'VeChain', symbol: 'VET', generator: 'evm', params: {}, category: 'EVM Chain', color: '#15BDFF', parentChain: 'EVM' },
  { id: 'one', name: 'Harmony', symbol: 'ONE', generator: 'evm', params: {}, category: 'EVM Chain', color: '#00ADE8', parentChain: 'EVM' },

  // ── Cosmos Ecosystem ──
  { id: 'atom', name: 'Cosmos Hub', symbol: 'ATOM', generator: 'cosmos', params: { prefix: 'cosmos' }, category: 'Cosmos', color: '#2E3148' },
  { id: 'osmo', name: 'Osmosis', symbol: 'OSMO', generator: 'cosmos', params: { prefix: 'osmo' }, category: 'Cosmos', color: '#750BBB' },
  { id: 'inj', name: 'Injective', symbol: 'INJ', generator: 'cosmos', params: { prefix: 'inj' }, category: 'Cosmos', color: '#00F2FE' },
  { id: 'sei', name: 'Sei', symbol: 'SEI', generator: 'cosmos', params: { prefix: 'sei' }, category: 'Cosmos', color: '#9B1C2E' },
  { id: 'tia', name: 'Celestia', symbol: 'TIA', generator: 'cosmos', params: { prefix: 'celestia' }, category: 'Cosmos', color: '#7B2BF9' },
  { id: 'dydx', name: 'dYdX', symbol: 'DYDX', generator: 'cosmos', params: { prefix: 'dydx' }, category: 'Cosmos', color: '#6966FF' },
  { id: 'kava', name: 'Kava', symbol: 'KAVA', generator: 'cosmos', params: { prefix: 'kava' }, category: 'Cosmos', color: '#FF564F' },
  { id: 'akt', name: 'Akash', symbol: 'AKT', generator: 'cosmos', params: { prefix: 'akash' }, category: 'Cosmos', color: '#FF414C' },
  { id: 'scrt', name: 'Secret Network', symbol: 'SCRT', generator: 'cosmos', params: { prefix: 'secret' }, category: 'Cosmos', color: '#1B1B1B' },
  { id: 'strd', name: 'Stride', symbol: 'STRD', generator: 'cosmos', params: { prefix: 'stride' }, category: 'Cosmos', color: '#E91179' },
  { id: 'juno', name: 'Juno', symbol: 'JUNO', generator: 'cosmos', params: { prefix: 'juno' }, category: 'Cosmos', color: '#F0827D' },
  { id: 'regen', name: 'Regen Network', symbol: 'REGEN', generator: 'cosmos', params: { prefix: 'regen' }, category: 'Cosmos', color: '#56B77B' },

  // ── Stablecoins (ERC-20) ──
  { id: 'usdt', name: 'Tether', symbol: 'USDT', generator: 'evm', params: {}, category: 'Stablecoin', color: '#26A17B', parentChain: 'Ethereum' },
  { id: 'usdc', name: 'USD Coin', symbol: 'USDC', generator: 'evm', params: {}, category: 'Stablecoin', color: '#2775CA', parentChain: 'Ethereum' },
  { id: 'dai', name: 'Dai', symbol: 'DAI', generator: 'evm', params: {}, category: 'Stablecoin', color: '#F5AC37', parentChain: 'Ethereum' },
  { id: 'tusd', name: 'TrueUSD', symbol: 'TUSD', generator: 'evm', params: {}, category: 'Stablecoin', color: '#2B2E7F', parentChain: 'Ethereum' },
  { id: 'frax', name: 'Frax', symbol: 'FRAX', generator: 'evm', params: {}, category: 'Stablecoin', color: '#000000', parentChain: 'Ethereum' },

  // ── DeFi (ERC-20) ──
  { id: 'uni', name: 'Uniswap', symbol: 'UNI', generator: 'evm', params: {}, category: 'DeFi', color: '#FF007A', parentChain: 'Ethereum' },
  { id: 'aave', name: 'Aave', symbol: 'AAVE', generator: 'evm', params: {}, category: 'DeFi', color: '#B6509E', parentChain: 'Ethereum' },
  { id: 'mkr', name: 'Maker', symbol: 'MKR', generator: 'evm', params: {}, category: 'DeFi', color: '#1AAB9B', parentChain: 'Ethereum' },
  { id: 'ldo', name: 'Lido DAO', symbol: 'LDO', generator: 'evm', params: {}, category: 'DeFi', color: '#00A3FF', parentChain: 'Ethereum' },
  { id: 'snx', name: 'Synthetix', symbol: 'SNX', generator: 'evm', params: {}, category: 'DeFi', color: '#00D1FF', parentChain: 'Ethereum' },
  { id: 'comp', name: 'Compound', symbol: 'COMP', generator: 'evm', params: {}, category: 'DeFi', color: '#00D395', parentChain: 'Ethereum' },
  { id: 'crv', name: 'Curve DAO', symbol: 'CRV', generator: 'evm', params: {}, category: 'DeFi', color: '#FF2D55', parentChain: 'Ethereum' },
  { id: '1inch', name: '1inch', symbol: '1INCH', generator: 'evm', params: {}, category: 'DeFi', color: '#94A6C3', parentChain: 'Ethereum' },
  { id: 'pendle', name: 'Pendle', symbol: 'PENDLE', generator: 'evm', params: {}, category: 'DeFi', color: '#1C7ED6', parentChain: 'Ethereum' },
  { id: 'eigen', name: 'EigenLayer', symbol: 'EIGEN', generator: 'evm', params: {}, category: 'DeFi', color: '#1A0533', parentChain: 'Ethereum' },
  { id: 'ena', name: 'Ethena', symbol: 'ENA', generator: 'evm', params: {}, category: 'DeFi', color: '#1C1C1C', parentChain: 'Ethereum' },
  { id: 'ondo', name: 'Ondo Finance', symbol: 'ONDO', generator: 'evm', params: {}, category: 'DeFi', color: '#1A3C78', parentChain: 'Ethereum' },
  { id: 'steth', name: 'Lido stETH', symbol: 'stETH', generator: 'evm', params: {}, category: 'DeFi', color: '#00A3FF', parentChain: 'Ethereum' },
  { id: 'wbtc', name: 'Wrapped Bitcoin', symbol: 'WBTC', generator: 'evm', params: {}, category: 'DeFi', color: '#F09242', parentChain: 'Ethereum' },

  // ── Infrastructure (ERC-20) ──
  { id: 'link', name: 'Chainlink', symbol: 'LINK', generator: 'evm', params: {}, category: 'Infrastructure', color: '#2A5ADA', parentChain: 'Ethereum' },
  { id: 'grt', name: 'The Graph', symbol: 'GRT', generator: 'evm', params: {}, category: 'Infrastructure', color: '#6747ED', parentChain: 'Ethereum' },
  { id: 'rndr', name: 'Render', symbol: 'RNDR', generator: 'evm', params: {}, category: 'Infrastructure', color: '#1E1E1E', parentChain: 'Ethereum' },
  { id: 'fet', name: 'Fetch.ai', symbol: 'FET', generator: 'evm', params: {}, category: 'Infrastructure', color: '#202537', parentChain: 'Ethereum' },
  { id: 'qnt', name: 'Quant', symbol: 'QNT', generator: 'evm', params: {}, category: 'Infrastructure', color: '#000000', parentChain: 'Ethereum' },
  { id: 'theta', name: 'Theta Network', symbol: 'THETA', generator: 'evm', params: {}, category: 'Infrastructure', color: '#2AB8E6', parentChain: 'Ethereum' },
  { id: 'imx', name: 'Immutable', symbol: 'IMX', generator: 'evm', params: {}, category: 'Infrastructure', color: '#00C3FF', parentChain: 'Ethereum' },
  { id: 'wld', name: 'Worldcoin', symbol: 'WLD', generator: 'evm', params: {}, category: 'Infrastructure', color: '#000000', parentChain: 'Ethereum' },
  { id: 'ar', name: 'Arweave', symbol: 'AR', generator: 'evm', params: {}, category: 'Infrastructure', color: '#222326', parentChain: 'Ethereum' },

  // ── Memecoins ──
  { id: 'shib', name: 'Shiba Inu', symbol: 'SHIB', generator: 'evm', params: {}, category: 'Memecoin', color: '#FFA409', parentChain: 'Ethereum' },
  { id: 'pepe', name: 'Pepe', symbol: 'PEPE', generator: 'evm', params: {}, category: 'Memecoin', color: '#009933', parentChain: 'Ethereum' },
  { id: 'floki', name: 'Floki', symbol: 'FLOKI', generator: 'evm', params: {}, category: 'Memecoin', color: '#D7A84A', parentChain: 'Ethereum' },
  { id: 'bonk', name: 'Bonk', symbol: 'BONK', generator: 'solana', params: {}, category: 'Memecoin', color: '#F9A825', parentChain: 'Solana' },
  { id: 'wif', name: 'dogwifhat', symbol: 'WIF', generator: 'solana', params: {}, category: 'Memecoin', color: '#A0522D', parentChain: 'Solana' },

  // ── Gaming & NFT (ERC-20) ──
  { id: 'axs', name: 'Axie Infinity', symbol: 'AXS', generator: 'evm', params: {}, category: 'Gaming', color: '#0055D5', parentChain: 'Ethereum' },
  { id: 'sand', name: 'The Sandbox', symbol: 'SAND', generator: 'evm', params: {}, category: 'Gaming', color: '#04ADEF', parentChain: 'Ethereum' },
  { id: 'mana', name: 'Decentraland', symbol: 'MANA', generator: 'evm', params: {}, category: 'Gaming', color: '#FF2D55', parentChain: 'Ethereum' },
  { id: 'gala', name: 'Gala', symbol: 'GALA', generator: 'evm', params: {}, category: 'Gaming', color: '#000000', parentChain: 'Ethereum' },
  { id: 'enj', name: 'Enjin Coin', symbol: 'ENJ', generator: 'evm', params: {}, category: 'Gaming', color: '#624DBF', parentChain: 'Ethereum' },
  { id: 'ape', name: 'ApeCoin', symbol: 'APE', generator: 'evm', params: {}, category: 'Gaming', color: '#0054F7', parentChain: 'Ethereum' },
  { id: 'ilv', name: 'Illuvium', symbol: 'ILV', generator: 'evm', params: {}, category: 'Gaming', color: '#C63AEA', parentChain: 'Ethereum' },

  // ── Solana SPL Tokens ──
  { id: 'jup', name: 'Jupiter', symbol: 'JUP', generator: 'solana', params: {}, category: 'DeFi', color: '#31D0AA', parentChain: 'Solana' },
  { id: 'ray', name: 'Raydium', symbol: 'RAY', generator: 'solana', params: {}, category: 'DeFi', color: '#7B46F6', parentChain: 'Solana' },
  { id: 'pyth', name: 'Pyth Network', symbol: 'PYTH', generator: 'solana', params: {}, category: 'Infrastructure', color: '#E6DAFE', parentChain: 'Solana' },
  { id: 'jto', name: 'Jito', symbol: 'JTO', generator: 'solana', params: {}, category: 'DeFi', color: '#67E8C4', parentChain: 'Solana' },
  { id: 'mnde', name: 'Marinade', symbol: 'MNDE', generator: 'solana', params: {}, category: 'DeFi', color: '#4E9A6D', parentChain: 'Solana' },

  // ── Additional EVM Chains ──
  { id: 'aurora', name: 'Aurora', symbol: 'AURORA', generator: 'evm', params: {}, category: 'EVM Chain', color: '#78D64B', parentChain: 'EVM' },
  { id: 'boba', name: 'Boba Network', symbol: 'BOBA', generator: 'evm', params: {}, category: 'EVM Chain', color: '#CBFF00', parentChain: 'EVM' },
  { id: 'movr', name: 'Moonriver', symbol: 'MOVR', generator: 'evm', params: {}, category: 'EVM Chain', color: '#F2B705', parentChain: 'EVM' },
  { id: 'skl', name: 'SKALE', symbol: 'SKL', generator: 'evm', params: {}, category: 'EVM Chain', color: '#4A90D9', parentChain: 'EVM' },
  { id: 'rose', name: 'Oasis Network', symbol: 'ROSE', generator: 'evm', params: {}, category: 'EVM Chain', color: '#0092F6', parentChain: 'EVM' },
  { id: 'zora', name: 'Zora', symbol: 'ZORA', generator: 'evm', params: {}, category: 'EVM Chain', color: '#2B5DF0', parentChain: 'EVM' },
  { id: 'mode', name: 'Mode', symbol: 'MODE', generator: 'evm', params: {}, category: 'EVM Chain', color: '#DFFE00', parentChain: 'EVM' },
  { id: 'taiko', name: 'Taiko', symbol: 'TAIKO', generator: 'evm', params: {}, category: 'EVM Chain', color: '#E81899', parentChain: 'EVM' },
  { id: 'manta', name: 'Manta Pacific', symbol: 'MANTA', generator: 'evm', params: {}, category: 'EVM Chain', color: '#1098FC', parentChain: 'EVM' },
  { id: 'astr', name: 'Astar', symbol: 'ASTR', generator: 'evm', params: {}, category: 'EVM Chain', color: '#0070EB', parentChain: 'EVM' },

  // ── Additional DeFi (ERC-20) ──
  { id: 'sushi', name: 'SushiSwap', symbol: 'SUSHI', generator: 'evm', params: {}, category: 'DeFi', color: '#FA52A0', parentChain: 'Ethereum' },
  { id: 'yfi', name: 'Yearn Finance', symbol: 'YFI', generator: 'evm', params: {}, category: 'DeFi', color: '#006AE3', parentChain: 'Ethereum' },
  { id: 'bal', name: 'Balancer', symbol: 'BAL', generator: 'evm', params: {}, category: 'DeFi', color: '#1E1E1E', parentChain: 'Ethereum' },
  { id: 'gmx', name: 'GMX', symbol: 'GMX', generator: 'evm', params: {}, category: 'DeFi', color: '#1A1B2F', parentChain: 'Ethereum' },
  { id: 'rpl', name: 'Rocket Pool', symbol: 'RPL', generator: 'evm', params: {}, category: 'DeFi', color: '#E8754A', parentChain: 'Ethereum' },
  { id: 'cvx', name: 'Convex Finance', symbol: 'CVX', generator: 'evm', params: {}, category: 'DeFi', color: '#3A82F7', parentChain: 'Ethereum' },
  { id: 'blur', name: 'Blur', symbol: 'BLUR', generator: 'evm', params: {}, category: 'DeFi', color: '#FF6B00', parentChain: 'Ethereum' },
  { id: 'lrc', name: 'Loopring', symbol: 'LRC', generator: 'evm', params: {}, category: 'DeFi', color: '#1C60FF', parentChain: 'Ethereum' },
  { id: 'ssv', name: 'SSV Network', symbol: 'SSV', generator: 'evm', params: {}, category: 'DeFi', color: '#4A90D9', parentChain: 'Ethereum' },
  { id: 'dodo', name: 'DODO', symbol: 'DODO', generator: 'evm', params: {}, category: 'DeFi', color: '#FFE804', parentChain: 'Ethereum' },
  { id: 'bnt', name: 'Bancor', symbol: 'BNT', generator: 'evm', params: {}, category: 'DeFi', color: '#010E2B', parentChain: 'Ethereum' },
  { id: 'knc', name: 'Kyber Network', symbol: 'KNC', generator: 'evm', params: {}, category: 'DeFi', color: '#31CB9E', parentChain: 'Ethereum' },
  { id: 'ankr', name: 'Ankr', symbol: 'ANKR', generator: 'evm', params: {}, category: 'DeFi', color: '#2E6FF9', parentChain: 'Ethereum' },
  { id: 'dydx_eth', name: 'dYdX (ERC-20)', symbol: 'ethDYDX', generator: 'evm', params: {}, category: 'DeFi', color: '#6966FF', parentChain: 'Ethereum' },

  // ── Additional Infrastructure (ERC-20) ──
  { id: 'ocean', name: 'Ocean Protocol', symbol: 'OCEAN', generator: 'evm', params: {}, category: 'Infrastructure', color: '#141414', parentChain: 'Ethereum' },
  { id: 'api3', name: 'API3', symbol: 'API3', generator: 'evm', params: {}, category: 'Infrastructure', color: '#3E4FA0', parentChain: 'Ethereum' },
  { id: 'storj', name: 'Storj', symbol: 'STORJ', generator: 'evm', params: {}, category: 'Infrastructure', color: '#2683FF', parentChain: 'Ethereum' },
  { id: 'lpt', name: 'Livepeer', symbol: 'LPT', generator: 'evm', params: {}, category: 'Infrastructure', color: '#00EB88', parentChain: 'Ethereum' },
  { id: 'mask', name: 'Mask Network', symbol: 'MASK', generator: 'evm', params: {}, category: 'Infrastructure', color: '#1C68F3', parentChain: 'Ethereum' },
  { id: 'bat', name: 'Basic Attention', symbol: 'BAT', generator: 'evm', params: {}, category: 'Infrastructure', color: '#FF5000', parentChain: 'Ethereum' },
  { id: 'zrx', name: '0x Protocol', symbol: 'ZRX', generator: 'evm', params: {}, category: 'Infrastructure', color: '#302C2C', parentChain: 'Ethereum' },
  { id: 'trb', name: 'Tellor', symbol: 'TRB', generator: 'evm', params: {}, category: 'Infrastructure', color: '#20F092', parentChain: 'Ethereum' },
  { id: 'req', name: 'Request', symbol: 'REQ', generator: 'evm', params: {}, category: 'Infrastructure', color: '#00E6A0', parentChain: 'Ethereum' },
  { id: 'band', name: 'Band Protocol', symbol: 'BAND', generator: 'evm', params: {}, category: 'Infrastructure', color: '#516AFF', parentChain: 'Ethereum' },
  { id: 'nmr', name: 'Numeraire', symbol: 'NMR', generator: 'evm', params: {}, category: 'Infrastructure', color: '#101010', parentChain: 'Ethereum' },
  { id: 'rlc', name: 'iExec RLC', symbol: 'RLC', generator: 'evm', params: {}, category: 'Infrastructure', color: '#FFD800', parentChain: 'Ethereum' },

  // ── Additional Stablecoins ──
  { id: 'pyusd', name: 'PayPal USD', symbol: 'PYUSD', generator: 'evm', params: {}, category: 'Stablecoin', color: '#0070BA', parentChain: 'Ethereum' },
  { id: 'fdusd', name: 'First Digital USD', symbol: 'FDUSD', generator: 'evm', params: {}, category: 'Stablecoin', color: '#25B896', parentChain: 'Ethereum' },
  { id: 'lusd', name: 'Liquity USD', symbol: 'LUSD', generator: 'evm', params: {}, category: 'Stablecoin', color: '#2EB6EA', parentChain: 'Ethereum' },
  { id: 'gusd', name: 'Gemini Dollar', symbol: 'GUSD', generator: 'evm', params: {}, category: 'Stablecoin', color: '#00DCFA', parentChain: 'Ethereum' },
  { id: 'usdd', name: 'USDD', symbol: 'USDD', generator: 'tron', params: {}, category: 'Stablecoin', color: '#1CE7E0', parentChain: 'Tron' },
  { id: 'crvusd', name: 'Curve USD', symbol: 'crvUSD', generator: 'evm', params: {}, category: 'Stablecoin', color: '#FF2D55', parentChain: 'Ethereum' },
  { id: 'gho', name: 'GHO', symbol: 'GHO', generator: 'evm', params: {}, category: 'Stablecoin', color: '#B6509E', parentChain: 'Ethereum' },

  // ── Additional Memecoins ──
  { id: 'turbo', name: 'Turbo', symbol: 'TURBO', generator: 'evm', params: {}, category: 'Memecoin', color: '#FF7700', parentChain: 'Ethereum' },
  { id: 'meme', name: 'Memecoin', symbol: 'MEME', generator: 'evm', params: {}, category: 'Memecoin', color: '#CB6CE6', parentChain: 'Ethereum' },
  { id: 'neiro', name: 'Neiro', symbol: 'NEIRO', generator: 'evm', params: {}, category: 'Memecoin', color: '#FFB800', parentChain: 'Ethereum' },
  { id: 'bome', name: 'Book of Meme', symbol: 'BOME', generator: 'solana', params: {}, category: 'Memecoin', color: '#B0F542', parentChain: 'Solana' },
  { id: 'mew', name: 'cat in a dogs world', symbol: 'MEW', generator: 'solana', params: {}, category: 'Memecoin', color: '#9B59B6', parentChain: 'Solana' },
  { id: 'popcat', name: 'Popcat', symbol: 'POPCAT', generator: 'solana', params: {}, category: 'Memecoin', color: '#FF4081', parentChain: 'Solana' },
  { id: 'myro', name: 'Myro', symbol: 'MYRO', generator: 'solana', params: {}, category: 'Memecoin', color: '#FF6B00', parentChain: 'Solana' },
  { id: 'samo', name: 'Samoyedcoin', symbol: 'SAMO', generator: 'solana', params: {}, category: 'Memecoin', color: '#E8E8E8', parentChain: 'Solana' },
  { id: 'babydoge', name: 'Baby Doge', symbol: 'BABYDOGE', generator: 'evm', params: {}, category: 'Memecoin', color: '#F5A623', parentChain: 'Ethereum' },

  // ── Additional Cosmos Ecosystem ──
  { id: 'axl', name: 'Axelar', symbol: 'AXL', generator: 'cosmos', params: { prefix: 'axelar' }, category: 'Cosmos', color: '#2A2C36' },
  { id: 'xprt', name: 'Persistence', symbol: 'XPRT', generator: 'cosmos', params: { prefix: 'persistence' }, category: 'Cosmos', color: '#E50914' },
  { id: 'somm', name: 'Sommelier', symbol: 'SOMM', generator: 'cosmos', params: { prefix: 'somm' }, category: 'Cosmos', color: '#FA7268' },
  { id: 'evmos', name: 'Evmos', symbol: 'EVMOS', generator: 'cosmos', params: { prefix: 'evmos' }, category: 'Cosmos', color: '#ED4E33' },
  { id: 'canto', name: 'Canto', symbol: 'CANTO', generator: 'cosmos', params: { prefix: 'canto' }, category: 'Cosmos', color: '#06FC99' },
  { id: 'flix', name: 'OmniFlix', symbol: 'FLIX', generator: 'cosmos', params: { prefix: 'omniflix' }, category: 'Cosmos', color: '#C2185B' },
  { id: 'stars', name: 'Stargaze', symbol: 'STARS', generator: 'cosmos', params: { prefix: 'stars' }, category: 'Cosmos', color: '#DB2777' },
  { id: 'ntrn', name: 'Neutron', symbol: 'NTRN', generator: 'cosmos', params: { prefix: 'neutron' }, category: 'Cosmos', color: '#000000' },

  // ── Additional Gaming & NFT ──
  { id: 'gmt', name: 'STEPN', symbol: 'GMT', generator: 'solana', params: {}, category: 'Gaming', color: '#BDFF00', parentChain: 'Solana' },
  { id: 'atlas', name: 'Star Atlas', symbol: 'ATLAS', generator: 'solana', params: {}, category: 'Gaming', color: '#FF3D71', parentChain: 'Solana' },
  { id: 'gods', name: 'Gods Unchained', symbol: 'GODS', generator: 'evm', params: {}, category: 'Gaming', color: '#3C3C3C', parentChain: 'Ethereum' },
  { id: 'ygg', name: 'Yield Guild', symbol: 'YGG', generator: 'evm', params: {}, category: 'Gaming', color: '#9747FF', parentChain: 'Ethereum' },
  { id: 'magic', name: 'Treasure', symbol: 'MAGIC', generator: 'evm', params: {}, category: 'Gaming', color: '#DC2626', parentChain: 'Ethereum' },
  { id: 'beam', name: 'Beam', symbol: 'BEAM', generator: 'evm', params: {}, category: 'Gaming', color: '#FEEE2E', parentChain: 'Ethereum' },
  { id: 'prime', name: 'Echelon Prime', symbol: 'PRIME', generator: 'evm', params: {}, category: 'Gaming', color: '#FB4B4E', parentChain: 'Ethereum' },
  { id: 'super', name: 'SuperVerse', symbol: 'SUPER', generator: 'evm', params: {}, category: 'Gaming', color: '#1E3A5F', parentChain: 'Ethereum' },
  { id: 'pixel', name: 'Pixels', symbol: 'PIXEL', generator: 'evm', params: {}, category: 'Gaming', color: '#6C5CE7', parentChain: 'Ethereum' },
  { id: 'portal', name: 'Portal', symbol: 'PORTAL', generator: 'evm', params: {}, category: 'Gaming', color: '#0076FF', parentChain: 'Ethereum' },

  // ── Additional Solana SPL ──
  { id: 'orca', name: 'Orca', symbol: 'ORCA', generator: 'solana', params: {}, category: 'DeFi', color: '#FFD15C', parentChain: 'Solana' },
  { id: 'tnsr', name: 'Tensor', symbol: 'TNSR', generator: 'solana', params: {}, category: 'Infrastructure', color: '#4E44CE', parentChain: 'Solana' },
  { id: 'hnt', name: 'Helium', symbol: 'HNT', generator: 'solana', params: {}, category: 'Infrastructure', color: '#474DFF', parentChain: 'Solana' },
  { id: 'drift', name: 'Drift', symbol: 'DRIFT', generator: 'solana', params: {}, category: 'DeFi', color: '#E851EB', parentChain: 'Solana' },
  { id: 'w', name: 'Wormhole', symbol: 'W', generator: 'solana', params: {}, category: 'Infrastructure', color: '#C1C1C1', parentChain: 'Solana' },
  { id: 'render_sol', name: 'Render (Solana)', symbol: 'RENDER', generator: 'solana', params: {}, category: 'Infrastructure', color: '#1E1E1E', parentChain: 'Solana' },
  { id: 'mobile', name: 'Helium Mobile', symbol: 'MOBILE', generator: 'solana', params: {}, category: 'Infrastructure', color: '#2BC3FF', parentChain: 'Solana' },

  // ── Additional Bitcoin Forks ──
  { id: 'nmc', name: 'Namecoin', symbol: 'NMC', generator: 'btc-legacy', params: { versionByte: 0x34, wifByte: 0xb4 }, category: 'Bitcoin Fork', color: '#186C9A' },
  { id: 'vtc', name: 'Vertcoin', symbol: 'VTC', generator: 'btc-legacy', params: { versionByte: 0x47, wifByte: 0x80 }, category: 'Bitcoin Fork', color: '#048657' },
  { id: 'ppc', name: 'Peercoin', symbol: 'PPC', generator: 'btc-legacy', params: { versionByte: 0x37, wifByte: 0xb7 }, category: 'Bitcoin Fork', color: '#3CB054' },
  { id: 'ftc', name: 'Feathercoin', symbol: 'FTC', generator: 'btc-legacy', params: { versionByte: 0x0e, wifByte: 0x8e }, category: 'Bitcoin Fork', color: '#27323A' },
  { id: 'via', name: 'Viacoin', symbol: 'VIA', generator: 'btc-legacy', params: { versionByte: 0x47, wifByte: 0xc7 }, category: 'Bitcoin Fork', color: '#565656' },
];
