import type { CoinDefinition } from './types';

export const coins: CoinDefinition[] = [
  // ── Layer 1 Blockchains ──
  { id: 'shrd', name: 'ShardCoin', symbol: 'SHRD', generator: 'btc-legacy', params: { versionByte: 0x3f, wifByte: 0xbf }, category: 'Layer 1', color: '#6C3AED' },
  { id: 'btc', name: 'Bitcoin', symbol: 'BTC', generator: 'btc-segwit', params: { hrp: 'bc' }, category: 'Layer 1', color: '#F7931A' },
  { id: 'eth', name: 'Ethereum', symbol: 'ETH', generator: 'evm', params: {}, category: 'Layer 1', color: '#627EEA' },
  { id: 'sol', name: 'Solana', symbol: 'SOL', generator: 'solana', params: {}, category: 'Layer 1', color: '#9945FF' },
  { id: 'xrp', name: 'XRP', symbol: 'XRP', generator: 'xrp', params: {}, category: 'Layer 1', color: '#23292F' },
  { id: 'ada', name: 'Cardano', symbol: 'ADA', generator: 'cardano', params: {}, category: 'Layer 1', color: '#0033AD' },
  { id: 'trx', name: 'Tron', symbol: 'TRX', generator: 'tron', params: {}, category: 'Layer 1', color: '#FF0013' },
  { id: 'avax', name: 'Avalanche', symbol: 'AVAX', generator: 'evm', params: {}, category: 'Layer 1', color: '#E84142' },
  { id: 'dot', name: 'Polkadot', symbol: 'DOT', generator: 'polkadot', params: { networkId: 0 }, category: 'Layer 1', color: '#E6007A' },
  { id: 'ton', name: 'Toncoin', symbol: 'TON', generator: 'ton', params: {}, category: 'Layer 1', color: '#0098EA' },
  { id: 'near', name: 'NEAR Protocol', symbol: 'NEAR', generator: 'near', params: {}, category: 'Layer 1', color: '#00C08B' },
  { id: 'apt', name: 'Aptos', symbol: 'APT', generator: 'aptos', params: {}, category: 'Layer 1', color: '#4DC9B0' },
  { id: 'sui', name: 'Sui', symbol: 'SUI', generator: 'sui', params: {}, category: 'Layer 1', color: '#4DA2FF' },
  { id: 'algo', name: 'Algorand', symbol: 'ALGO', generator: 'algorand', params: {}, category: 'Layer 1', color: '#000000' },
  { id: 'xtz', name: 'Tezos', symbol: 'XTZ', generator: 'tezos', params: {}, category: 'Layer 1', color: '#2C7DF7' },
  { id: 'fil', name: 'Filecoin', symbol: 'FIL', generator: 'filecoin', params: {}, category: 'Layer 1', color: '#0090FF' },
  { id: 'xlm', name: 'Stellar', symbol: 'XLM', generator: 'stellar', params: {}, category: 'Layer 1', color: '#14B6E7' },
  { id: 'hbar', name: 'Hedera', symbol: 'HBAR', generator: 'hedera', params: {}, category: 'Layer 1', color: '#3A3A3A' },
  { id: 'xmr', name: 'Monero', symbol: 'XMR', generator: 'monero', params: {}, category: 'Layer 1', color: '#FF6600' },
  { id: 'eos', name: 'EOS', symbol: 'EOS', generator: 'eos', params: {}, category: 'Layer 1', color: '#443F54' },
  { id: 'ksm', name: 'Kusama', symbol: 'KSM', generator: 'polkadot', params: { networkId: 2 }, category: 'Layer 1', color: '#E6007A' },

  // ── Bitcoin Forks ──
  { id: 'ltc', name: 'Litecoin', symbol: 'LTC', generator: 'btc-legacy', params: { versionByte: 0x30, wifByte: 0xb0 }, category: 'Bitcoin Fork', color: '#BFBBBB' },
  { id: 'doge', name: 'Dogecoin', symbol: 'DOGE', generator: 'btc-legacy', params: { versionByte: 0x1e, wifByte: 0x9e }, category: 'Bitcoin Fork', color: '#C2A633' },
  { id: 'bch', name: 'Bitcoin Cash', symbol: 'BCH', generator: 'btc-legacy', params: { versionByte: 0x00, wifByte: 0x80 }, category: 'Bitcoin Fork', color: '#0AC18E' },
  { id: 'dash', name: 'Dash', symbol: 'DASH', generator: 'btc-legacy', params: { versionByte: 0x4c, wifByte: 0xcc }, category: 'Bitcoin Fork', color: '#008CE7' },
  { id: 'zec', name: 'Zcash', symbol: 'ZEC', generator: 'btc-legacy', params: { versionByte: [0x1c, 0xb8], wifByte: 0x80 }, category: 'Bitcoin Fork', color: '#F4B728' },
  { id: 'dgb', name: 'DigiByte', symbol: 'DGB', generator: 'btc-legacy', params: { versionByte: 0x1e, wifByte: 0x80 }, category: 'Bitcoin Fork', color: '#006AD2' },
  { id: 'rvn', name: 'Ravencoin', symbol: 'RVN', generator: 'btc-legacy', params: { versionByte: 0x3c, wifByte: 0x80 }, category: 'Bitcoin Fork', color: '#384182' },
  { id: 'bsv', name: 'Bitcoin SV', symbol: 'BSV', generator: 'btc-legacy', params: { versionByte: 0x00, wifByte: 0x80 }, category: 'Bitcoin Fork', color: '#EAB300' },
  { id: 'dcr', name: 'Decred', symbol: 'DCR', generator: 'btc-legacy', params: { versionByte: [0x07, 0x3f], wifByte: 0x80 }, category: 'Bitcoin Fork', color: '#2ED6A1' },
  { id: 'zen', name: 'Horizen', symbol: 'ZEN', generator: 'btc-legacy', params: { versionByte: [0x20, 0x89], wifByte: 0x80 }, category: 'Bitcoin Fork', color: '#00A98D' },
  { id: 'sys', name: 'Syscoin', symbol: 'SYS', generator: 'btc-legacy', params: { versionByte: 0x3f, wifByte: 0xbf }, category: 'Bitcoin Fork', color: '#0082C6' },

  // ── EVM Chains ──
  { id: 'bnb', name: 'BNB Smart Chain', symbol: 'BNB', generator: 'evm', params: {}, category: 'EVM Chain', color: '#F0B90B', parentChain: 'EVM' },
  { id: 'pol', name: 'Polygon', symbol: 'POL', generator: 'evm', params: {}, category: 'EVM Chain', color: '#8247E5', parentChain: 'EVM' },
  { id: 'arb', name: 'Arbitrum', symbol: 'ARB', generator: 'evm', params: {}, category: 'EVM Chain', color: '#28A0F0', parentChain: 'EVM' },
  { id: 'op', name: 'Optimism', symbol: 'OP', generator: 'evm', params: {}, category: 'EVM Chain', color: '#FF0420', parentChain: 'EVM' },
  { id: 'base', name: 'Base', symbol: 'BASE', generator: 'evm', params: {}, category: 'EVM Chain', color: '#0052FF', parentChain: 'EVM' },
  { id: 'ftm', name: 'Fantom', symbol: 'FTM', generator: 'evm', params: {}, category: 'EVM Chain', color: '#1969FF', parentChain: 'EVM' },
  { id: 'cro', name: 'Cronos', symbol: 'CRO', generator: 'evm', params: {}, category: 'EVM Chain', color: '#002D74', parentChain: 'EVM' },
  { id: 'mnt', name: 'Mantle', symbol: 'MNT', generator: 'evm', params: {}, category: 'EVM Chain', color: '#000000' , parentChain: 'EVM' },
  { id: 'celo', name: 'Celo', symbol: 'CELO', generator: 'evm', params: {}, category: 'EVM Chain', color: '#FBCC5C', parentChain: 'EVM' },
  { id: 'glmr', name: 'Moonbeam', symbol: 'GLMR', generator: 'evm', params: {}, category: 'EVM Chain', color: '#53CBC9', parentChain: 'EVM' },
  { id: 'metis', name: 'Metis', symbol: 'METIS', generator: 'evm', params: {}, category: 'EVM Chain', color: '#00DACC', parentChain: 'EVM' },
  { id: 'klay', name: 'Klaytn', symbol: 'KLAY', generator: 'evm', params: {}, category: 'EVM Chain', color: '#4F473B', parentChain: 'EVM' },
  { id: 'gno', name: 'Gnosis', symbol: 'GNO', generator: 'evm', params: {}, category: 'EVM Chain', color: '#04795B', parentChain: 'EVM' },
  { id: 'linea', name: 'Linea', symbol: 'LINEA', generator: 'evm', params: {}, category: 'EVM Chain', color: '#121212', parentChain: 'EVM' },
  { id: 'scroll', name: 'Scroll', symbol: 'SCROLL', generator: 'evm', params: {}, category: 'EVM Chain', color: '#FFEEDA', parentChain: 'EVM' },
  { id: 'zksync', name: 'zkSync Era', symbol: 'ZK', generator: 'evm', params: {}, category: 'EVM Chain', color: '#4E529A', parentChain: 'EVM' },
  { id: 'blast', name: 'Blast', symbol: 'BLAST', generator: 'evm', params: {}, category: 'EVM Chain', color: '#FCFC03', parentChain: 'EVM' },
  { id: 'flr', name: 'Flare', symbol: 'FLR', generator: 'evm', params: {}, category: 'EVM Chain', color: '#E42058', parentChain: 'EVM' },
  { id: 'vet', name: 'VeChain', symbol: 'VET', generator: 'evm', params: {}, category: 'EVM Chain', color: '#15BDFF', parentChain: 'EVM' },
  { id: 'one', name: 'Harmony', symbol: 'ONE', generator: 'evm', params: {}, category: 'EVM Chain', color: '#00ADE8', parentChain: 'EVM' },

  // ── Cosmos Ecosystem ──
  { id: 'atom', name: 'Cosmos Hub', symbol: 'ATOM', generator: 'cosmos', params: { prefix: 'cosmos' }, category: 'Cosmos', color: '#2E3148' },
  { id: 'osmo', name: 'Osmosis', symbol: 'OSMO', generator: 'cosmos', params: { prefix: 'osmo' }, category: 'Cosmos', color: '#750BBB' },
  { id: 'inj', name: 'Injective', symbol: 'INJ', generator: 'cosmos', params: { prefix: 'inj' }, category: 'Cosmos', color: '#00F2FE' },
  { id: 'sei', name: 'Sei', symbol: 'SEI', generator: 'cosmos', params: { prefix: 'sei' }, category: 'Cosmos', color: '#9B1C2E' },
  { id: 'tia', name: 'Celestia', symbol: 'TIA', generator: 'cosmos', params: { prefix: 'celestia' }, category: 'Cosmos', color: '#7B2BF9' },
  { id: 'dydx', name: 'dYdX', symbol: 'DYDX', generator: 'cosmos', params: { prefix: 'dydx' }, category: 'Cosmos', color: '#6966FF' },
  { id: 'kava', name: 'Kava', symbol: 'KAVA', generator: 'cosmos', params: { prefix: 'kava' }, category: 'Cosmos', color: '#FF564F' },
  { id: 'akt', name: 'Akash', symbol: 'AKT', generator: 'cosmos', params: { prefix: 'akash' }, category: 'Cosmos', color: '#FF414C' },
  { id: 'scrt', name: 'Secret Network', symbol: 'SCRT', generator: 'cosmos', params: { prefix: 'secret' }, category: 'Cosmos', color: '#1B1B1B' },
  { id: 'strd', name: 'Stride', symbol: 'STRD', generator: 'cosmos', params: { prefix: 'stride' }, category: 'Cosmos', color: '#E91179' },
  { id: 'juno', name: 'Juno', symbol: 'JUNO', generator: 'cosmos', params: { prefix: 'juno' }, category: 'Cosmos', color: '#F0827D' },
  { id: 'regen', name: 'Regen Network', symbol: 'REGEN', generator: 'cosmos', params: { prefix: 'regen' }, category: 'Cosmos', color: '#56B77B' },

  // ── Stablecoins (ERC-20) ──
  { id: 'usdt', name: 'Tether', symbol: 'USDT', generator: 'evm', params: {}, category: 'Stablecoin', color: '#26A17B', parentChain: 'Ethereum' },
  { id: 'usdc', name: 'USD Coin', symbol: 'USDC', generator: 'evm', params: {}, category: 'Stablecoin', color: '#2775CA', parentChain: 'Ethereum' },
  { id: 'dai', name: 'Dai', symbol: 'DAI', generator: 'evm', params: {}, category: 'Stablecoin', color: '#F5AC37', parentChain: 'Ethereum' },
  { id: 'tusd', name: 'TrueUSD', symbol: 'TUSD', generator: 'evm', params: {}, category: 'Stablecoin', color: '#2B2E7F', parentChain: 'Ethereum' },
  { id: 'frax', name: 'Frax', symbol: 'FRAX', generator: 'evm', params: {}, category: 'Stablecoin', color: '#000000', parentChain: 'Ethereum' },

  // ── DeFi (ERC-20) ──
  { id: 'uni', name: 'Uniswap', symbol: 'UNI', generator: 'evm', params: {}, category: 'DeFi', color: '#FF007A', parentChain: 'Ethereum' },
  { id: 'aave', name: 'Aave', symbol: 'AAVE', generator: 'evm', params: {}, category: 'DeFi', color: '#B6509E', parentChain: 'Ethereum' },
  { id: 'mkr', name: 'Maker', symbol: 'MKR', generator: 'evm', params: {}, category: 'DeFi', color: '#1AAB9B', parentChain: 'Ethereum' },
  { id: 'ldo', name: 'Lido DAO', symbol: 'LDO', generator: 'evm', params: {}, category: 'DeFi', color: '#00A3FF', parentChain: 'Ethereum' },
  { id: 'snx', name: 'Synthetix', symbol: 'SNX', generator: 'evm', params: {}, category: 'DeFi', color: '#00D1FF', parentChain: 'Ethereum' },
  { id: 'comp', name: 'Compound', symbol: 'COMP', generator: 'evm', params: {}, category: 'DeFi', color: '#00D395', parentChain: 'Ethereum' },
  { id: 'crv', name: 'Curve DAO', symbol: 'CRV', generator: 'evm', params: {}, category: 'DeFi', color: '#FF2D55', parentChain: 'Ethereum' },
  { id: '1inch', name: '1inch', symbol: '1INCH', generator: 'evm', params: {}, category: 'DeFi', color: '#94A6C3', parentChain: 'Ethereum' },
  { id: 'pendle', name: 'Pendle', symbol: 'PENDLE', generator: 'evm', params: {}, category: 'DeFi', color: '#1C7ED6', parentChain: 'Ethereum' },
  { id: 'eigen', name: 'EigenLayer', symbol: 'EIGEN', generator: 'evm', params: {}, category: 'DeFi', color: '#1A0533', parentChain: 'Ethereum' },
  { id: 'ena', name: 'Ethena', symbol: 'ENA', generator: 'evm', params: {}, category: 'DeFi', color: '#1C1C1C', parentChain: 'Ethereum' },
  { id: 'ondo', name: 'Ondo Finance', symbol: 'ONDO', generator: 'evm', params: {}, category: 'DeFi', color: '#1A3C78', parentChain: 'Ethereum' },
  { id: 'steth', name: 'Lido stETH', symbol: 'stETH', generator: 'evm', params: {}, category: 'DeFi', color: '#00A3FF', parentChain: 'Ethereum' },
  { id: 'wbtc', name: 'Wrapped Bitcoin', symbol: 'WBTC', generator: 'evm', params: {}, category: 'DeFi', color: '#F09242', parentChain: 'Ethereum' },

  // ── Infrastructure (ERC-20) ──
  { id: 'link', name: 'Chainlink', symbol: 'LINK', generator: 'evm', params: {}, category: 'Infrastructure', color: '#2A5ADA', parentChain: 'Ethereum' },
  { id: 'grt', name: 'The Graph', symbol: 'GRT', generator: 'evm', params: {}, category: 'Infrastructure', color: '#6747ED', parentChain: 'Ethereum' },
  { id: 'rndr', name: 'Render', symbol: 'RNDR', generator: 'evm', params: {}, category: 'Infrastructure', color: '#1E1E1E', parentChain: 'Ethereum' },
  { id: 'fet', name: 'Fetch.ai', symbol: 'FET', generator: 'evm', params: {}, category: 'Infrastructure', color: '#202537', parentChain: 'Ethereum' },
  { id: 'qnt', name: 'Quant', symbol: 'QNT', generator: 'evm', params: {}, category: 'Infrastructure', color: '#000000', parentChain: 'Ethereum' },
  { id: 'theta', name: 'Theta Network', symbol: 'THETA', generator: 'evm', params: {}, category: 'Infrastructure', color: '#2AB8E6', parentChain: 'Ethereum' },
  { id: 'imx', name: 'Immutable', symbol: 'IMX', generator: 'evm', params: {}, category: 'Infrastructure', color: '#00C3FF', parentChain: 'Ethereum' },
  { id: 'wld', name: 'Worldcoin', symbol: 'WLD', generator: 'evm', params: {}, category: 'Infrastructure', color: '#000000', parentChain: 'Ethereum' },
  { id: 'ar', name: 'Arweave', symbol: 'AR', generator: 'evm', params: {}, category: 'Infrastructure', color: '#222326', parentChain: 'Ethereum' },

  // ── Memecoins ──
  { id: 'shib', name: 'Shiba Inu', symbol: 'SHIB', generator: 'evm', params: {}, category: 'Memecoin', color: '#FFA409', parentChain: 'Ethereum' },
  { id: 'pepe', name: 'Pepe', symbol: 'PEPE', generator: 'evm', params: {}, category: 'Memecoin', color: '#009933', parentChain: 'Ethereum' },
  { id: 'floki', name: 'Floki', symbol: 'FLOKI', generator: 'evm', params: {}, category: 'Memecoin', color: '#D7A84A', parentChain: 'Ethereum' },
  { id: 'bonk', name: 'Bonk', symbol: 'BONK', generator: 'solana', params: {}, category: 'Memecoin', color: '#F9A825', parentChain: 'Solana' },
  { id: 'wif', name: 'dogwifhat', symbol: 'WIF', generator: 'solana', params: {}, category: 'Memecoin', color: '#A0522D', parentChain: 'Solana' },

  // ── Gaming & NFT (ERC-20) ──
  { id: 'axs', name: 'Axie Infinity', symbol: 'AXS', generator: 'evm', params: {}, category: 'Gaming', color: '#0055D5', parentChain: 'Ethereum' },
  { id: 'sand', name: 'The Sandbox', symbol: 'SAND', generator: 'evm', params: {}, category: 'Gaming', color: '#04ADEF', parentChain: 'Ethereum' },
  { id: 'mana', name: 'Decentraland', symbol: 'MANA', generator: 'evm', params: {}, category: 'Gaming', color: '#FF2D55', parentChain: 'Ethereum' },
  { id: 'gala', name: 'Gala', symbol: 'GALA', generator: 'evm', params: {}, category: 'Gaming', color: '#000000', parentChain: 'Ethereum' },
  { id: 'enj', name: 'Enjin Coin', symbol: 'ENJ', generator: 'evm', params: {}, category: 'Gaming', color: '#624DBF', parentChain: 'Ethereum' },
  { id: 'ape', name: 'ApeCoin', symbol: 'APE', generator: 'evm', params: {}, category: 'Gaming', color: '#0054F7', parentChain: 'Ethereum' },
  { id: 'ilv', name: 'Illuvium', symbol: 'ILV', generator: 'evm', params: {}, category: 'Gaming', color: '#C63AEA', parentChain: 'Ethereum' },

  // ── Solana SPL Tokens ──
  { id: 'jup', name: 'Jupiter', symbol: 'JUP', generator: 'solana', params: {}, category: 'DeFi', color: '#31D0AA', parentChain: 'Solana' },
  { id: 'ray', name: 'Raydium', symbol: 'RAY', generator: 'solana', params: {}, category: 'DeFi', color: '#7B46F6', parentChain: 'Solana' },
  { id: 'pyth', name: 'Pyth Network', symbol: 'PYTH', generator: 'solana', params: {}, category: 'Infrastructure', color: '#E6DAFE', parentChain: 'Solana' },
  { id: 'jto', name: 'Jito', symbol: 'JTO', generator: 'solana', params: {}, category: 'DeFi', color: '#67E8C4', parentChain: 'Solana' },
  { id: 'mnde', name: 'Marinade', symbol: 'MNDE', generator: 'solana', params: {}, category: 'DeFi', color: '#4E9A6D', parentChain: 'Solana' },

  // ── Additional EVM Chains ──
  { id: 'aurora', name: 'Aurora', symbol: 'AURORA', generator: 'evm', params: {}, category: 'EVM Chain', color: '#78D64B', parentChain: 'EVM' },
  { id: 'boba', name: 'Boba Network', symbol: 'BOBA', generator: 'evm', params: {}, category: 'EVM Chain', color: '#CBFF00', parentChain: 'EVM' },
  { id: 'movr', name: 'Moonriver', symbol: 'MOVR', generator: 'evm', params: {}, category: 'EVM Chain', color: '#F2B705', parentChain: 'EVM' },
  { id: 'skl', name: 'SKALE', symbol: 'SKL', generator: 'evm', params: {}, category: 'EVM Chain', color: '#4A90D9', parentChain: 'EVM' },
  { id: 'rose', name: 'Oasis Network', symbol: 'ROSE', generator: 'evm', params: {}, category: 'EVM Chain', color: '#0092F6', parentChain: 'EVM' },
  { id: 'zora', name: 'Zora', symbol: 'ZORA', generator: 'evm', params: {}, category: 'EVM Chain', color: '#2B5DF0', parentChain: 'EVM' },
  { id: 'mode', name: 'Mode', symbol: 'MODE', generator: 'evm', params: {}, category: 'EVM Chain', color: '#DFFE00', parentChain: 'EVM' },
  { id: 'taiko', name: 'Taiko', symbol: 'TAIKO', generator: 'evm', params: {}, category: 'EVM Chain', color: '#E81899', parentChain: 'EVM' },
  { id: 'manta', name: 'Manta Pacific', symbol: 'MANTA', generator: 'evm', params: {}, category: 'EVM Chain', color: '#1098FC', parentChain: 'EVM' },
  { id: 'astr', name: 'Astar', symbol: 'ASTR', generator: 'evm', params: {}, category: 'EVM Chain', color: '#0070EB', parentChain: 'EVM' },

  // ── Additional DeFi (ERC-20) ──
  { id: 'sushi', name: 'SushiSwap', symbol: 'SUSHI', generator: 'evm', params: {}, category: 'DeFi', color: '#FA52A0', parentChain: 'Ethereum' },
  { id: 'yfi', name: 'Yearn Finance', symbol: 'YFI', generator: 'evm', params: {}, category: 'DeFi', color: '#006AE3', parentChain: 'Ethereum' },
  { id: 'bal', name: 'Balancer', symbol: 'BAL', generator: 'evm', params: {}, category: 'DeFi', color: '#1E1E1E', parentChain: 'Ethereum' },
  { id: 'gmx', name: 'GMX', symbol: 'GMX', generator: 'evm', params: {}, category: 'DeFi', color: '#1A1B2F', parentChain: 'Ethereum' },
  { id: 'rpl', name: 'Rocket Pool', symbol: 'RPL', generator: 'evm', params: {}, category: 'DeFi', color: '#E8754A', parentChain: 'Ethereum' },
  { id: 'cvx', name: 'Convex Finance', symbol: 'CVX', generator: 'evm', params: {}, category: 'DeFi', color: '#3A82F7', parentChain: 'Ethereum' },
  { id: 'blur', name: 'Blur', symbol: 'BLUR', generator: 'evm', params: {}, category: 'DeFi', color: '#FF6B00', parentChain: 'Ethereum' },
  { id: 'lrc', name: 'Loopring', symbol: 'LRC', generator: 'evm', params: {}, category: 'DeFi', color: '#1C60FF', parentChain: 'Ethereum' },
  { id: 'ssv', name: 'SSV Network', symbol: 'SSV', generator: 'evm', params: {}, category: 'DeFi', color: '#4A90D9', parentChain: 'Ethereum' },
  { id: 'dodo', name: 'DODO', symbol: 'DODO', generator: 'evm', params: {}, category: 'DeFi', color: '#FFE804', parentChain: 'Ethereum' },
  { id: 'bnt', name: 'Bancor', symbol: 'BNT', generator: 'evm', params: {}, category: 'DeFi', color: '#010E2B', parentChain: 'Ethereum' },
  { id: 'knc', name: 'Kyber Network', symbol: 'KNC', generator: 'evm', params: {}, category: 'DeFi', color: '#31CB9E', parentChain: 'Ethereum' },
  { id: 'ankr', name: 'Ankr', symbol: 'ANKR', generator: 'evm', params: {}, category: 'DeFi', color: '#2E6FF9', parentChain: 'Ethereum' },
  { id: 'dydx_eth', name: 'dYdX (ERC-20)', symbol: 'ethDYDX', generator: 'evm', params: {}, category: 'DeFi', color: '#6966FF', parentChain: 'Ethereum' },

  // ── Additional Infrastructure (ERC-20) ──
  { id: 'ocean', name: 'Ocean Protocol', symbol: 'OCEAN', generator: 'evm', params: {}, category: 'Infrastructure', color: '#141414', parentChain: 'Ethereum' },
  { id: 'api3', name: 'API3', symbol: 'API3', generator: 'evm', params: {}, category: 'Infrastructure', color: '#3E4FA0', parentChain: 'Ethereum' },
  { id: 'storj', name: 'Storj', symbol: 'STORJ', generator: 'evm', params: {}, category: 'Infrastructure', color: '#2683FF', parentChain: 'Ethereum' },
  { id: 'lpt', name: 'Livepeer', symbol: 'LPT', generator: 'evm', params: {}, category: 'Infrastructure', color: '#00EB88', parentChain: 'Ethereum' },
  { id: 'mask', name: 'Mask Network', symbol: 'MASK', generator: 'evm', params: {}, category: 'Infrastructure', color: '#1C68F3', parentChain: 'Ethereum' },
  { id: 'bat', name: 'Basic Attention', symbol: 'BAT', generator: 'evm', params: {}, category: 'Infrastructure', color: '#FF5000', parentChain: 'Ethereum' },
  { id: 'zrx', name: '0x Protocol', symbol: 'ZRX', generator: 'evm', params: {}, category: 'Infrastructure', color: '#302C2C', parentChain: 'Ethereum' },
  { id: 'trb', name: 'Tellor', symbol: 'TRB', generator: 'evm', params: {}, category: 'Infrastructure', color: '#20F092', parentChain: 'Ethereum' },
  { id: 'req', name: 'Request', symbol: 'REQ', generator: 'evm', params: {}, category: 'Infrastructure', color: '#00E6A0', parentChain: 'Ethereum' },
  { id: 'band', name: 'Band Protocol', symbol: 'BAND', generator: 'evm', params: {}, category: 'Infrastructure', color: '#516AFF', parentChain: 'Ethereum' },
  { id: 'nmr', name: 'Numeraire', symbol: 'NMR', generator: 'evm', params: {}, category: 'Infrastructure', color: '#101010', parentChain: 'Ethereum' },
  { id: 'rlc', name: 'iExec RLC', symbol: 'RLC', generator: 'evm', params: {}, category: 'Infrastructure', color: '#FFD800', parentChain: 'Ethereum' },

  // ── Additional Stablecoins ──
  { id: 'pyusd', name: 'PayPal USD', symbol: 'PYUSD', generator: 'evm', params: {}, category: 'Stablecoin', color: '#0070BA', parentChain: 'Ethereum' },
  { id: 'fdusd', name: 'First Digital USD', symbol: 'FDUSD', generator: 'evm', params: {}, category: 'Stablecoin', color: '#25B896', parentChain: 'Ethereum' },
  { id: 'lusd', name: 'Liquity USD', symbol: 'LUSD', generator: 'evm', params: {}, category: 'Stablecoin', color: '#2EB6EA', parentChain: 'Ethereum' },
  { id: 'gusd', name: 'Gemini Dollar', symbol: 'GUSD', generator: 'evm', params: {}, category: 'Stablecoin', color: '#00DCFA', parentChain: 'Ethereum' },
  { id: 'usdd', name: 'USDD', symbol: 'USDD', generator: 'tron', params: {}, category: 'Stablecoin', color: '#1CE7E0', parentChain: 'Tron' },
  { id: 'crvusd', name: 'Curve USD', symbol: 'crvUSD', generator: 'evm', params: {}, category: 'Stablecoin', color: '#FF2D55', parentChain: 'Ethereum' },
  { id: 'gho', name: 'GHO', symbol: 'GHO', generator: 'evm', params: {}, category: 'Stablecoin', color: '#B6509E', parentChain: 'Ethereum' },

  // ── Additional Memecoins ──
  { id: 'turbo', name: 'Turbo', symbol: 'TURBO', generator: 'evm', params: {}, category: 'Memecoin', color: '#FF7700', parentChain: 'Ethereum' },
  { id: 'meme', name: 'Memecoin', symbol: 'MEME', generator: 'evm', params: {}, category: 'Memecoin', color: '#CB6CE6', parentChain: 'Ethereum' },
  { id: 'neiro', name: 'Neiro', symbol: 'NEIRO', generator: 'evm', params: {}, category: 'Memecoin', color: '#FFB800', parentChain: 'Ethereum' },
  { id: 'bome', name: 'Book of Meme', symbol: 'BOME', generator: 'solana', params: {}, category: 'Memecoin', color: '#B0F542', parentChain: 'Solana' },
  { id: 'mew', name: 'cat in a dogs world', symbol: 'MEW', generator: 'solana', params: {}, category: 'Memecoin', color: '#9B59B6', parentChain: 'Solana' },
  { id: 'popcat', name: 'Popcat', symbol: 'POPCAT', generator: 'solana', params: {}, category: 'Memecoin', color: '#FF4081', parentChain: 'Solana' },
  { id: 'myro', name: 'Myro', symbol: 'MYRO', generator: 'solana', params: {}, category: 'Memecoin', color: '#FF6B00', parentChain: 'Solana' },
  { id: 'samo', name: 'Samoyedcoin', symbol: 'SAMO', generator: 'solana', params: {}, category: 'Memecoin', color: '#E8E8E8', parentChain: 'Solana' },
  { id: 'babydoge', name: 'Baby Doge', symbol: 'BABYDOGE', generator: 'evm', params: {}, category: 'Memecoin', color: '#F5A623', parentChain: 'Ethereum' },

  // ── Additional Cosmos Ecosystem ──
  { id: 'axl', name: 'Axelar', symbol: 'AXL', generator: 'cosmos', params: { prefix: 'axelar' }, category: 'Cosmos', color: '#2A2C36' },
  { id: 'xprt', name: 'Persistence', symbol: 'XPRT', generator: 'cosmos', params: { prefix: 'persistence' }, category: 'Cosmos', color: '#E50914' },
  { id: 'somm', name: 'Sommelier', symbol: 'SOMM', generator: 'cosmos', params: { prefix: 'somm' }, category: 'Cosmos', color: '#FA7268' },
  { id: 'evmos', name: 'Evmos', symbol: 'EVMOS', generator: 'cosmos', params: { prefix: 'evmos' }, category: 'Cosmos', color: '#ED4E33' },
  { id: 'canto', name: 'Canto', symbol: 'CANTO', generator: 'cosmos', params: { prefix: 'canto' }, category: 'Cosmos', color: '#06FC99' },
  { id: 'flix', name: 'OmniFlix', symbol: 'FLIX', generator: 'cosmos', params: { prefix: 'omniflix' }, category: 'Cosmos', color: '#C2185B' },
  { id: 'stars', name: 'Stargaze', symbol: 'STARS', generator: 'cosmos', params: { prefix: 'stars' }, category: 'Cosmos', color: '#DB2777' },
  { id: 'ntrn', name: 'Neutron', symbol: 'NTRN', generator: 'cosmos', params: { prefix: 'neutron' }, category: 'Cosmos', color: '#000000' },

  // ── Additional Gaming & NFT ──
  { id: 'gmt', name: 'STEPN', symbol: 'GMT', generator: 'solana', params: {}, category: 'Gaming', color: '#BDFF00', parentChain: 'Solana' },
  { id: 'atlas', name: 'Star Atlas', symbol: 'ATLAS', generator: 'solana', params: {}, category: 'Gaming', color: '#FF3D71', parentChain: 'Solana' },
  { id: 'gods', name: 'Gods Unchained', symbol: 'GODS', generator: 'evm', params: {}, category: 'Gaming', color: '#3C3C3C', parentChain: 'Ethereum' },
  { id: 'ygg', name: 'Yield Guild', symbol: 'YGG', generator: 'evm', params: {}, category: 'Gaming', color: '#9747FF', parentChain: 'Ethereum' },
  { id: 'magic', name: 'Treasure', symbol: 'MAGIC', generator: 'evm', params: {}, category: 'Gaming', color: '#DC2626', parentChain: 'Ethereum' },
  { id: 'beam', name: 'Beam', symbol: 'BEAM', generator: 'evm', params: {}, category: 'Gaming', color: '#FEEE2E', parentChain: 'Ethereum' },
  { id: 'prime', name: 'Echelon Prime', symbol: 'PRIME', generator: 'evm', params: {}, category: 'Gaming', color: '#FB4B4E', parentChain: 'Ethereum' },
  { id: 'super', name: 'SuperVerse', symbol: 'SUPER', generator: 'evm', params: {}, category: 'Gaming', color: '#1E3A5F', parentChain: 'Ethereum' },
  { id: 'pixel', name: 'Pixels', symbol: 'PIXEL', generator: 'evm', params: {}, category: 'Gaming', color: '#6C5CE7', parentChain: 'Ethereum' },
  { id: 'portal', name: 'Portal', symbol: 'PORTAL', generator: 'evm', params: {}, category: 'Gaming', color: '#0076FF', parentChain: 'Ethereum' },

  // ── Additional Solana SPL ──
  { id: 'orca', name: 'Orca', symbol: 'ORCA', generator: 'solana', params: {}, category: 'DeFi', color: '#FFD15C', parentChain: 'Solana' },
  { id: 'tnsr', name: 'Tensor', symbol: 'TNSR', generator: 'solana', params: {}, category: 'Infrastructure', color: '#4E44CE', parentChain: 'Solana' },
  { id: 'hnt', name: 'Helium', symbol: 'HNT', generator: 'solana', params: {}, category: 'Infrastructure', color: '#474DFF', parentChain: 'Solana' },
  { id: 'drift', name: 'Drift', symbol: 'DRIFT', generator: 'solana', params: {}, category: 'DeFi', color: '#E851EB', parentChain: 'Solana' },
  { id: 'w', name: 'Wormhole', symbol: 'W', generator: 'solana', params: {}, category: 'Infrastructure', color: '#C1C1C1', parentChain: 'Solana' },
  { id: 'render_sol', name: 'Render (Solana)', symbol: 'RENDER', generator: 'solana', params: {}, category: 'Infrastructure', color: '#1E1E1E', parentChain: 'Solana' },
  { id: 'mobile', name: 'Helium Mobile', symbol: 'MOBILE', generator: 'solana', params: {}, category: 'Infrastructure', color: '#2BC3FF', parentChain: 'Solana' },

  // ── Additional Bitcoin Forks ──
  { id: 'nmc', name: 'Namecoin', symbol: 'NMC', generator: 'btc-legacy', params: { versionByte: 0x34, wifByte: 0xb4 }, category: 'Bitcoin Fork', color: '#186C9A' },
  { id: 'vtc', name: 'Vertcoin', symbol: 'VTC', generator: 'btc-legacy', params: { versionByte: 0x47, wifByte: 0x80 }, category: 'Bitcoin Fork', color: '#048657' },
  { id: 'ppc', name: 'Peercoin', symbol: 'PPC', generator: 'btc-legacy', params: { versionByte: 0x37, wifByte: 0xb7 }, category: 'Bitcoin Fork', color: '#3CB054' },
  { id: 'ftc', name: 'Feathercoin', symbol: 'FTC', generator: 'btc-legacy', params: { versionByte: 0x0e, wifByte: 0x8e }, category: 'Bitcoin Fork', color: '#27323A' },
  { id: 'via', name: 'Viacoin', symbol: 'VIA', generator: 'btc-legacy', params: { versionByte: 0x47, wifByte: 0xc7 }, category: 'Bitcoin Fork', color: '#565656' },

  // ── Additional Layer 1 ──
  { id: 'icp', name: 'Internet Computer', symbol: 'ICP', generator: 'evm', params: {}, category: 'Layer 1', color: '#29ABE2' },
  { id: 'stx', name: 'Stacks', symbol: 'STX', generator: 'btc-legacy', params: { versionByte: 0x16, wifByte: 0x80 }, category: 'Layer 1', color: '#5546FF' },
  { id: 'egld', name: 'MultiversX', symbol: 'EGLD', generator: 'evm', params: {}, category: 'Layer 1', color: '#23F7DD' },
  { id: 'flow', name: 'Flow', symbol: 'FLOW', generator: 'evm', params: {}, category: 'Layer 1', color: '#00EF8B' },
  { id: 'mina', name: 'Mina Protocol', symbol: 'MINA', generator: 'evm', params: {}, category: 'Layer 1', color: '#E49B13' },
  { id: 'neo', name: 'Neo', symbol: 'NEO', generator: 'evm', params: {}, category: 'Layer 1', color: '#00E599' },
  { id: 'waves', name: 'Waves', symbol: 'WAVES', generator: 'evm', params: {}, category: 'Layer 1', color: '#0055FF' },
  { id: 'zil', name: 'Zilliqa', symbol: 'ZIL', generator: 'evm', params: {}, category: 'Layer 1', color: '#49C1BF' },
  { id: 'iota', name: 'IOTA', symbol: 'IOTA', generator: 'evm', params: {}, category: 'Layer 1', color: '#242424' },
  { id: 'kas', name: 'Kaspa', symbol: 'KAS', generator: 'evm', params: {}, category: 'Layer 1', color: '#49EACB' },

  // ── More EVM Chains ──
  { id: 'ethw', name: 'Ethereum PoW', symbol: 'ETHW', generator: 'evm', params: {}, category: 'EVM Chain', color: '#627EEA', parentChain: 'EVM' },
  { id: 'etc', name: 'Ethereum Classic', symbol: 'ETC', generator: 'evm', params: {}, category: 'EVM Chain', color: '#328332', parentChain: 'EVM' },
  { id: 'iotx', name: 'IoTeX', symbol: 'IOTX', generator: 'evm', params: {}, category: 'EVM Chain', color: '#44FFB2', parentChain: 'EVM' },
  { id: 'sx', name: 'SX Network', symbol: 'SX', generator: 'evm', params: {}, category: 'EVM Chain', color: '#1C60FF', parentChain: 'EVM' },
  { id: 'neon', name: 'Neon EVM', symbol: 'NEON', generator: 'evm', params: {}, category: 'EVM Chain', color: '#E93EE9', parentChain: 'EVM' },
  { id: 'fuse', name: 'Fuse', symbol: 'FUSE', generator: 'evm', params: {}, category: 'EVM Chain', color: '#B4F94E', parentChain: 'EVM' },
  { id: 'telos', name: 'Telos EVM', symbol: 'TLOS', generator: 'evm', params: {}, category: 'EVM Chain', color: '#571AFF', parentChain: 'EVM' },
  { id: 'pgn', name: 'PGN', symbol: 'PGN', generator: 'evm', params: {}, category: 'EVM Chain', color: '#4F46E5', parentChain: 'EVM' },
  { id: 'kcc', name: 'KuCoin Chain', symbol: 'KCS', generator: 'evm', params: {}, category: 'EVM Chain', color: '#23AF91', parentChain: 'EVM' },
  { id: 'okt', name: 'OKT Chain', symbol: 'OKT', generator: 'evm', params: {}, category: 'EVM Chain', color: '#3C7EFF', parentChain: 'EVM' },

  // ── More DeFi ──
  { id: 'cake', name: 'PancakeSwap', symbol: 'CAKE', generator: 'evm', params: {}, category: 'DeFi', color: '#D1884F', parentChain: 'Ethereum' },
  { id: 'joe', name: 'Trader Joe', symbol: 'JOE', generator: 'evm', params: {}, category: 'DeFi', color: '#E94642', parentChain: 'Ethereum' },
  { id: 'spell', name: 'Spell Token', symbol: 'SPELL', generator: 'evm', params: {}, category: 'DeFi', color: '#824EE2', parentChain: 'Ethereum' },
  { id: 'stkGHO', name: 'Staked GHO', symbol: 'stkGHO', generator: 'evm', params: {}, category: 'DeFi', color: '#B6509E', parentChain: 'Ethereum' },
  { id: 'morpho', name: 'Morpho', symbol: 'MORPHO', generator: 'evm', params: {}, category: 'DeFi', color: '#1B1464', parentChain: 'Ethereum' },
  { id: 'rdnt', name: 'Radiant Capital', symbol: 'RDNT', generator: 'evm', params: {}, category: 'DeFi', color: '#00D4FF', parentChain: 'Ethereum' },
  { id: 'velo', name: 'Velodrome', symbol: 'VELO', generator: 'evm', params: {}, category: 'DeFi', color: '#0052FF', parentChain: 'Ethereum' },
  { id: 'aero', name: 'Aerodrome', symbol: 'AERO', generator: 'evm', params: {}, category: 'DeFi', color: '#0052FF', parentChain: 'Ethereum' },
  { id: 'usual', name: 'Usual', symbol: 'USUAL', generator: 'evm', params: {}, category: 'DeFi', color: '#000000', parentChain: 'Ethereum' },
  { id: 'sky', name: 'Sky', symbol: 'SKY', generator: 'evm', params: {}, category: 'DeFi', color: '#73CDFF', parentChain: 'Ethereum' },
  { id: 'ethfi', name: 'Ether.fi', symbol: 'ETHFI', generator: 'evm', params: {}, category: 'DeFi', color: '#7C3AED', parentChain: 'Ethereum' },
  { id: 'rseth', name: 'rsETH', symbol: 'rsETH', generator: 'evm', params: {}, category: 'DeFi', color: '#3B82F6', parentChain: 'Ethereum' },
  { id: 'reth', name: 'Rocket Pool ETH', symbol: 'rETH', generator: 'evm', params: {}, category: 'DeFi', color: '#E8754A', parentChain: 'Ethereum' },
  { id: 'cbeth', name: 'Coinbase stETH', symbol: 'cbETH', generator: 'evm', params: {}, category: 'DeFi', color: '#0052FF', parentChain: 'Ethereum' },

  // ── More Infrastructure ──
  { id: 'ens', name: 'ENS', symbol: 'ENS', generator: 'evm', params: {}, category: 'Infrastructure', color: '#5298FF', parentChain: 'Ethereum' },
  { id: 'safe', name: 'Safe', symbol: 'SAFE', generator: 'evm', params: {}, category: 'Infrastructure', color: '#12FF80', parentChain: 'Ethereum' },
  { id: 'matic_old', name: 'Polygon (old)', symbol: 'MATIC', generator: 'evm', params: {}, category: 'Infrastructure', color: '#8247E5', parentChain: 'Ethereum' },
  { id: 'gal', name: 'Galxe', symbol: 'GAL', generator: 'evm', params: {}, category: 'Infrastructure', color: '#000000', parentChain: 'Ethereum' },
  { id: 'cyber', name: 'CyberConnect', symbol: 'CYBER', generator: 'evm', params: {}, category: 'Infrastructure', color: '#000000', parentChain: 'Ethereum' },
  { id: 'dimo', name: 'DIMO', symbol: 'DIMO', generator: 'evm', params: {}, category: 'Infrastructure', color: '#43B1B1', parentChain: 'Ethereum' },
  { id: 'iotex_sol', name: 'Nosana', symbol: 'NOS', generator: 'solana', params: {}, category: 'Infrastructure', color: '#18181B', parentChain: 'Solana' },
  { id: 'io', name: 'io.net', symbol: 'IO', generator: 'solana', params: {}, category: 'Infrastructure', color: '#000000', parentChain: 'Solana' },
  { id: 'grass', name: 'Grass', symbol: 'GRASS', generator: 'solana', params: {}, category: 'Infrastructure', color: '#00C853', parentChain: 'Solana' },
  { id: 'ait', name: 'AIT Protocol', symbol: 'AIT', generator: 'evm', params: {}, category: 'Infrastructure', color: '#7C3AED', parentChain: 'Ethereum' },

  // ── More Cosmos ──
  { id: 'saga', name: 'Saga', symbol: 'SAGA', generator: 'cosmos', params: { prefix: 'saga' }, category: 'Cosmos', color: '#000000' },
  { id: 'dym', name: 'Dymension', symbol: 'DYM', generator: 'cosmos', params: { prefix: 'dym' }, category: 'Cosmos', color: '#FF5733' },
  { id: 'tori', name: 'Teritori', symbol: 'TORI', generator: 'cosmos', params: { prefix: 'tori' }, category: 'Cosmos', color: '#16A34A' },
  { id: 'lava', name: 'Lava Network', symbol: 'LAVA', generator: 'cosmos', params: { prefix: 'lava' }, category: 'Cosmos', color: '#FF4400' },
  { id: 'archway', name: 'Archway', symbol: 'ARCH', generator: 'cosmos', params: { prefix: 'archway' }, category: 'Cosmos', color: '#FF4D00' },
  { id: 'nibiru', name: 'Nibiru', symbol: 'NIBI', generator: 'cosmos', params: { prefix: 'nibi' }, category: 'Cosmos', color: '#5E2BFF' },

  // ── More Memecoins ──
  { id: 'trump', name: 'TRUMP', symbol: 'TRUMP', generator: 'solana', params: {}, category: 'Memecoin', color: '#B91C1C', parentChain: 'Solana' },
  { id: 'pnut', name: 'Peanut', symbol: 'PNUT', generator: 'solana', params: {}, category: 'Memecoin', color: '#D97706', parentChain: 'Solana' },
  { id: 'fartcoin', name: 'Fartcoin', symbol: 'FARTCOIN', generator: 'solana', params: {}, category: 'Memecoin', color: '#6B7280', parentChain: 'Solana' },
  { id: 'goat', name: 'Goatseus Maximus', symbol: 'GOAT', generator: 'solana', params: {}, category: 'Memecoin', color: '#84CC16', parentChain: 'Solana' },
  { id: 'act', name: 'Act I', symbol: 'ACT', generator: 'solana', params: {}, category: 'Memecoin', color: '#DC2626', parentChain: 'Solana' },
  { id: 'ai16z', name: 'ai16z', symbol: 'AI16Z', generator: 'solana', params: {}, category: 'Memecoin', color: '#2563EB', parentChain: 'Solana' },
  { id: 'griffain', name: 'Griffain', symbol: 'GRIFFAIN', generator: 'solana', params: {}, category: 'Memecoin', color: '#F59E0B', parentChain: 'Solana' },
  { id: 'moodeng', name: 'Moo Deng', symbol: 'MOODENG', generator: 'solana', params: {}, category: 'Memecoin', color: '#FB923C', parentChain: 'Solana' },
  { id: 'spx', name: 'SPX6900', symbol: 'SPX', generator: 'evm', params: {}, category: 'Memecoin', color: '#059669', parentChain: 'Ethereum' },
  { id: 'brett', name: 'Brett', symbol: 'BRETT', generator: 'evm', params: {}, category: 'Memecoin', color: '#2563EB', parentChain: 'Ethereum' },
  { id: 'toshi', name: 'Toshi', symbol: 'TOSHI', generator: 'evm', params: {}, category: 'Memecoin', color: '#3B82F6', parentChain: 'Ethereum' },
  { id: 'ladys', name: 'Milady', symbol: 'LADYS', generator: 'evm', params: {}, category: 'Memecoin', color: '#E879F9', parentChain: 'Ethereum' },
  { id: 'mother', name: 'Mother Iggy', symbol: 'MOTHER', generator: 'solana', params: {}, category: 'Memecoin', color: '#EC4899', parentChain: 'Solana' },

  // ── More Stablecoins ──
  { id: 'usde', name: 'USDe', symbol: 'USDe', generator: 'evm', params: {}, category: 'Stablecoin', color: '#1C1C1C', parentChain: 'Ethereum' },
  { id: 'mkusd', name: 'USDS', symbol: 'USDS', generator: 'evm', params: {}, category: 'Stablecoin', color: '#73CDFF', parentChain: 'Ethereum' },
  { id: 'eurc', name: 'Euro Coin', symbol: 'EURC', generator: 'evm', params: {}, category: 'Stablecoin', color: '#2775CA', parentChain: 'Ethereum' },
  { id: 'eur_t', name: 'Tether EUR', symbol: 'EURT', generator: 'evm', params: {}, category: 'Stablecoin', color: '#26A17B', parentChain: 'Ethereum' },

  // ── More Gaming ──
  { id: 'ron', name: 'Ronin', symbol: 'RON', generator: 'evm', params: {}, category: 'Gaming', color: '#1273EA', parentChain: 'EVM' },
  { id: 'imx_token', name: 'Immutable X', symbol: 'IMX', generator: 'evm', params: {}, category: 'Gaming', color: '#00C3FF', parentChain: 'Ethereum' },
  { id: 'xai', name: 'Xai', symbol: 'XAI', generator: 'evm', params: {}, category: 'Gaming', color: '#F5274E', parentChain: 'EVM' },
  { id: 'mavia', name: 'Heroes of Mavia', symbol: 'MAVIA', generator: 'evm', params: {}, category: 'Gaming', color: '#FF6B00', parentChain: 'Ethereum' },
  { id: 'nft', name: 'APENFT', symbol: 'NFT', generator: 'tron', params: {}, category: 'Gaming', color: '#2196F3', parentChain: 'Tron' },
  { id: 'polis', name: 'Star Atlas DAO', symbol: 'POLIS', generator: 'solana', params: {}, category: 'Gaming', color: '#FF3D71', parentChain: 'Solana' },
  { id: 'slp', name: 'Smooth Love Potion', symbol: 'SLP', generator: 'evm', params: {}, category: 'Gaming', color: '#F472B6', parentChain: 'Ethereum' },
  { id: 'gst', name: 'Green Satoshi', symbol: 'GST', generator: 'solana', params: {}, category: 'Gaming', color: '#BDFF00', parentChain: 'Solana' },

  // ── More Solana SPL ──
  { id: 'kmno', name: 'Kamino', symbol: 'KMNO', generator: 'solana', params: {}, category: 'DeFi', color: '#5B21B6', parentChain: 'Solana' },
  { id: 'sonic_sol', name: 'Sonic SVM', symbol: 'SONIC', generator: 'solana', params: {}, category: 'Infrastructure', color: '#1D4ED8', parentChain: 'Solana' },
  { id: 'me', name: 'Magic Eden', symbol: 'ME', generator: 'solana', params: {}, category: 'Infrastructure', color: '#E11D48', parentChain: 'Solana' },
  { id: 'zeta', name: 'ZetaChain', symbol: 'ZETA', generator: 'evm', params: {}, category: 'Infrastructure', color: '#00BC8D', parentChain: 'EVM' },
  { id: 'jlp', name: 'Jupiter LP', symbol: 'JLP', generator: 'solana', params: {}, category: 'DeFi', color: '#31D0AA', parentChain: 'Solana' },
  { id: 'msol', name: 'Marinade SOL', symbol: 'mSOL', generator: 'solana', params: {}, category: 'DeFi', color: '#4E9A6D', parentChain: 'Solana' },
  { id: 'jsol', name: 'JitoSOL', symbol: 'JITOSOL', generator: 'solana', params: {}, category: 'DeFi', color: '#67E8C4', parentChain: 'Solana' },
  { id: 'bsol', name: 'BlazeStake SOL', symbol: 'bSOL', generator: 'solana', params: {}, category: 'DeFi', color: '#F97316', parentChain: 'Solana' },

  // ── More Bitcoin Forks ──
  { id: 'pivx', name: 'PIVX', symbol: 'PIVX', generator: 'btc-legacy', params: { versionByte: 0x1e, wifByte: 0xd4 }, category: 'Bitcoin Fork', color: '#5E4778' },
  { id: 'firo', name: 'Firo', symbol: 'FIRO', generator: 'btc-legacy', params: { versionByte: 0x52, wifByte: 0xd2 }, category: 'Bitcoin Fork', color: '#9B1C1C' },
  { id: 'flux', name: 'Flux', symbol: 'FLUX', generator: 'btc-legacy', params: { versionByte: 0x1c, wifByte: 0x80 }, category: 'Bitcoin Fork', color: '#2B6CB0' },
  { id: 'xvg', name: 'Verge', symbol: 'XVG', generator: 'btc-legacy', params: { versionByte: 0x1e, wifByte: 0x9e }, category: 'Bitcoin Fork', color: '#00CBFF' },
  { id: 'btg', name: 'Bitcoin Gold', symbol: 'BTG', generator: 'btc-legacy', params: { versionByte: 0x26, wifByte: 0x80 }, category: 'Bitcoin Fork', color: '#EBA809' },

  // ══════════════════════════════════════════════════════════════════
  // 150 MORE BLOCKCHAINS
  // ══════════════════════════════════════════════════════════════════

  // ── EVM L1/L2 chains ──
  { id: 'canto_evm', name: 'Canto (EVM)', symbol: 'CANTO', generator: 'evm', params: {}, category: 'EVM Chain', color: '#06FC99', parentChain: 'EVM' },
  { id: 'pulse', name: 'PulseChain', symbol: 'PLS', generator: 'evm', params: {}, category: 'EVM Chain', color: '#1BF5AC', parentChain: 'EVM' },
  { id: 'zkevm', name: 'Polygon zkEVM', symbol: 'ZKEVM', generator: 'evm', params: {}, category: 'EVM Chain', color: '#8247E5', parentChain: 'EVM' },
  { id: 'core', name: 'Core', symbol: 'CORE', generator: 'evm', params: {}, category: 'EVM Chain', color: '#FF9211', parentChain: 'EVM' },
  { id: 'merlin', name: 'Merlin Chain', symbol: 'MERL', generator: 'evm', params: {}, category: 'EVM Chain', color: '#6D28D9', parentChain: 'EVM' },
  { id: 'bob', name: 'BOB', symbol: 'BOB', generator: 'evm', params: {}, category: 'EVM Chain', color: '#F97316', parentChain: 'EVM' },
  { id: 'bsquared', name: 'B² Network', symbol: 'B2', generator: 'evm', params: {}, category: 'EVM Chain', color: '#FF5C00', parentChain: 'EVM' },
  { id: 'bitlayer', name: 'Bitlayer', symbol: 'BTR', generator: 'evm', params: {}, category: 'EVM Chain', color: '#EAB308', parentChain: 'EVM' },
  { id: 'sei_evm', name: 'Sei EVM', symbol: 'SEIV2', generator: 'evm', params: {}, category: 'EVM Chain', color: '#9B1C2E', parentChain: 'EVM' },
  { id: 'apechain', name: 'ApeChain', symbol: 'APECHAIN', generator: 'evm', params: {}, category: 'EVM Chain', color: '#0054F7', parentChain: 'EVM' },
  { id: 'world', name: 'World Chain', symbol: 'WORLD', generator: 'evm', params: {}, category: 'EVM Chain', color: '#000000', parentChain: 'EVM' },
  { id: 'ink', name: 'Ink', symbol: 'INK', generator: 'evm', params: {}, category: 'EVM Chain', color: '#7C3AED', parentChain: 'EVM' },
  { id: 'soneium', name: 'Soneium', symbol: 'SONEIUM', generator: 'evm', params: {}, category: 'EVM Chain', color: '#4F46E5', parentChain: 'EVM' },
  { id: 'abstract', name: 'Abstract', symbol: 'ABS', generator: 'evm', params: {}, category: 'EVM Chain', color: '#00D4AA', parentChain: 'EVM' },
  { id: 'unichain', name: 'Unichain', symbol: 'UNICHAIN', generator: 'evm', params: {}, category: 'EVM Chain', color: '#FF007A', parentChain: 'EVM' },
  { id: 'morph', name: 'Morph', symbol: 'MORPH', generator: 'evm', params: {}, category: 'EVM Chain', color: '#00C48C', parentChain: 'EVM' },
  { id: 'zircuit', name: 'Zircuit', symbol: 'ZRC', generator: 'evm', params: {}, category: 'EVM Chain', color: '#60A5FA', parentChain: 'EVM' },
  { id: 'lisk', name: 'Lisk', symbol: 'LSK', generator: 'evm', params: {}, category: 'EVM Chain', color: '#0075BD', parentChain: 'EVM' },
  { id: 'rootstock', name: 'Rootstock', symbol: 'RBTC', generator: 'evm', params: {}, category: 'EVM Chain', color: '#00A651', parentChain: 'EVM' },
  { id: 'heco', name: 'Huobi ECO', symbol: 'HT', generator: 'evm', params: {}, category: 'EVM Chain', color: '#2D74E7', parentChain: 'EVM' },
  { id: 'wemix', name: 'WEMIX', symbol: 'WEMIX', generator: 'evm', params: {}, category: 'EVM Chain', color: '#9847FF', parentChain: 'EVM' },
  { id: 'thundercore', name: 'ThunderCore', symbol: 'TT', generator: 'evm', params: {}, category: 'EVM Chain', color: '#FFD800', parentChain: 'EVM' },
  { id: 'oasis_sapphire', name: 'Oasis Sapphire', symbol: 'ROSE2', generator: 'evm', params: {}, category: 'EVM Chain', color: '#0092F6', parentChain: 'EVM' },
  { id: 'beam_chain', name: 'Beam Chain', symbol: 'BEAM2', generator: 'evm', params: {}, category: 'EVM Chain', color: '#FEEE2E', parentChain: 'EVM' },
  { id: 'rari', name: 'RARI Chain', symbol: 'RARI', generator: 'evm', params: {}, category: 'EVM Chain', color: '#FEDA03', parentChain: 'EVM' },
  { id: 'cyber_chain', name: 'Cyber L2', symbol: 'CYBER2', generator: 'evm', params: {}, category: 'EVM Chain', color: '#000000', parentChain: 'EVM' },
  { id: 'mint', name: 'Mint', symbol: 'MINT', generator: 'evm', params: {}, category: 'EVM Chain', color: '#30D158', parentChain: 'EVM' },
  { id: 'degen', name: 'Degen L3', symbol: 'DEGEN', generator: 'evm', params: {}, category: 'EVM Chain', color: '#A855F7', parentChain: 'EVM' },
  { id: 'ham', name: 'Ham Chain', symbol: 'HAM', generator: 'evm', params: {}, category: 'EVM Chain', color: '#D2691E', parentChain: 'EVM' },
  { id: 'redstone', name: 'Redstone', symbol: 'REDSTONE', generator: 'evm', params: {}, category: 'EVM Chain', color: '#E11D48', parentChain: 'EVM' },

  // ── More Cosmos chains ──
  { id: 'band_chain', name: 'Band Protocol', symbol: 'BAND2', generator: 'cosmos', params: { prefix: 'band' }, category: 'Cosmos', color: '#516AFF' },
  { id: 'umee', name: 'UX (Umee)', symbol: 'UX', generator: 'cosmos', params: { prefix: 'umee' }, category: 'Cosmos', color: '#A855F7' },
  { id: 'mars', name: 'Mars Protocol', symbol: 'MARS', generator: 'cosmos', params: { prefix: 'mars' }, category: 'Cosmos', color: '#FF4B4B' },
  { id: 'comdex', name: 'Comdex', symbol: 'CMDX', generator: 'cosmos', params: { prefix: 'comdex' }, category: 'Cosmos', color: '#FE4350' },
  { id: 'quicksilver', name: 'Quicksilver', symbol: 'QCK', generator: 'cosmos', params: { prefix: 'quick' }, category: 'Cosmos', color: '#C0C0C0' },
  { id: 'composable', name: 'Composable', symbol: 'PICA', generator: 'cosmos', params: { prefix: 'pica' }, category: 'Cosmos', color: '#6B46C1' },
  { id: 'pryzm', name: 'Pryzm', symbol: 'PRYZM', generator: 'cosmos', params: { prefix: 'pryzm' }, category: 'Cosmos', color: '#EC4899' },
  { id: 'initia', name: 'Initia', symbol: 'INIT', generator: 'cosmos', params: { prefix: 'init' }, category: 'Cosmos', color: '#000000' },
  { id: 'babylon', name: 'Babylon', symbol: 'BABY', generator: 'cosmos', params: { prefix: 'bbn' }, category: 'Cosmos', color: '#FF6B00' },
  { id: 'mantra', name: 'MANTRA', symbol: 'OM', generator: 'cosmos', params: { prefix: 'mantra' }, category: 'Cosmos', color: '#E75425' },
  { id: 'nolus', name: 'Nolus', symbol: 'NLS', generator: 'cosmos', params: { prefix: 'nolus' }, category: 'Cosmos', color: '#2DD4BF' },
  { id: 'migaloo', name: 'Migaloo', symbol: 'WHALE', generator: 'cosmos', params: { prefix: 'migaloo' }, category: 'Cosmos', color: '#3B82F6' },
  { id: 'kuji', name: 'Kujira', symbol: 'KUJI', generator: 'cosmos', params: { prefix: 'kujira' }, category: 'Cosmos', color: '#E53E3E' },
  { id: 'coreum', name: 'Coreum', symbol: 'COREUM', generator: 'cosmos', params: { prefix: 'core' }, category: 'Cosmos', color: '#25D695' },
  { id: 'cheqd', name: 'cheqd', symbol: 'CHEQ', generator: 'cosmos', params: { prefix: 'cheqd' }, category: 'Cosmos', color: '#FF5C38' },

  // ── More Polkadot/Substrate ──
  { id: 'astar_sub', name: 'Astar (Substrate)', symbol: 'ASTR2', generator: 'polkadot', params: { networkId: 5 }, category: 'Layer 1', color: '#0070EB' },
  { id: 'phala', name: 'Phala Network', symbol: 'PHA', generator: 'polkadot', params: { networkId: 30 }, category: 'Layer 1', color: '#D1FF52' },
  { id: 'acala', name: 'Acala', symbol: 'ACA', generator: 'polkadot', params: { networkId: 10 }, category: 'Layer 1', color: '#E40C5B' },
  { id: 'bifrost', name: 'Bifrost', symbol: 'BNC', generator: 'polkadot', params: { networkId: 6 }, category: 'Layer 1', color: '#5445FF' },
  { id: 'nodle', name: 'Nodle', symbol: 'NODL', generator: 'polkadot', params: { networkId: 37 }, category: 'Layer 1', color: '#1D1D1B' },
  { id: 'zeitgeist', name: 'Zeitgeist', symbol: 'ZTG', generator: 'polkadot', params: { networkId: 73 }, category: 'Layer 1', color: '#0001FE' },
  { id: 'hydradx', name: 'HydraDX', symbol: 'HDX', generator: 'polkadot', params: { networkId: 63 }, category: 'Layer 1', color: '#4DBBFC' },
  { id: 'interlay', name: 'Interlay', symbol: 'INTR', generator: 'polkadot', params: { networkId: 2032 }, category: 'Layer 1', color: '#1A47B8' },
  { id: 'centrifuge', name: 'Centrifuge', symbol: 'CFG', generator: 'polkadot', params: { networkId: 36 }, category: 'Layer 1', color: '#000000' },
  { id: 'turing', name: 'Turing Network', symbol: 'TUR', generator: 'polkadot', params: { networkId: 51 }, category: 'Layer 1', color: '#3B82F6' },

  // ── More Bitcoin forks ──
  { id: 'groestl', name: 'Groestlcoin', symbol: 'GRS', generator: 'btc-legacy', params: { versionByte: 0x24, wifByte: 0x80 }, category: 'Bitcoin Fork', color: '#0B4B9B' },
  { id: 'mona', name: 'MonaCoin', symbol: 'MONA', generator: 'btc-legacy', params: { versionByte: 0x32, wifByte: 0xb0 }, category: 'Bitcoin Fork', color: '#DEC799' },
  { id: 'nbt', name: 'NIX', symbol: 'NIX', generator: 'btc-legacy', params: { versionByte: 0x26, wifByte: 0x80 }, category: 'Bitcoin Fork', color: '#6B3FA0' },
  { id: 'zcl', name: 'ZClassic', symbol: 'ZCL', generator: 'btc-legacy', params: { versionByte: [0x1c, 0xb8], wifByte: 0x80 }, category: 'Bitcoin Fork', color: '#C87035' },
  { id: 'btcp', name: 'Bitcoin Private', symbol: 'BTCP', generator: 'btc-legacy', params: { versionByte: [0x13, 0x25], wifByte: 0x80 }, category: 'Bitcoin Fork', color: '#272D63' },
  { id: 'grc', name: 'Gridcoin', symbol: 'GRC', generator: 'btc-legacy', params: { versionByte: 0x3e, wifByte: 0xbe }, category: 'Bitcoin Fork', color: '#5B2B82' },
  { id: 'bcd', name: 'Bitcoin Diamond', symbol: 'BCD', generator: 'btc-legacy', params: { versionByte: 0x00, wifByte: 0x80 }, category: 'Bitcoin Fork', color: '#F9A825' },
  { id: 'part', name: 'Particl', symbol: 'PART', generator: 'btc-legacy', params: { versionByte: 0x38, wifByte: 0x6c }, category: 'Bitcoin Fork', color: '#00E3A0' },
  { id: 'nav', name: 'NavCoin', symbol: 'NAV', generator: 'btc-legacy', params: { versionByte: 0x35, wifByte: 0x96 }, category: 'Bitcoin Fork', color: '#7D59B5' },
  { id: 'smart', name: 'SmartCash', symbol: 'SMART', generator: 'btc-legacy', params: { versionByte: 0x3f, wifByte: 0xbf }, category: 'Bitcoin Fork', color: '#FFC800' },

  // ── More Ed25519 chains ──
  { id: 'ckb', name: 'Nervos', symbol: 'CKB', generator: 'near', params: {}, category: 'Layer 1', color: '#3CC68A' },
  { id: 'rose_ed', name: 'Oasis (Ed25519)', symbol: 'ROSE3', generator: 'near', params: {}, category: 'Layer 1', color: '#0092F6' },
  { id: 'ar_native', name: 'Arweave Native', symbol: 'AR2', generator: 'near', params: {}, category: 'Layer 1', color: '#222326' },
  { id: 'sia', name: 'Siacoin', symbol: 'SC', generator: 'near', params: {}, category: 'Layer 1', color: '#20EE82' },
  { id: 'ergo', name: 'Ergo', symbol: 'ERG', generator: 'near', params: {}, category: 'Layer 1', color: '#FF5722' },

  // ── More Solana ecosystem ──
  { id: 'stepsol', name: 'Step Finance', symbol: 'STEP', generator: 'solana', params: {}, category: 'DeFi', color: '#06D6A0', parentChain: 'Solana' },
  { id: 'slnd', name: 'Solend', symbol: 'SLND', generator: 'solana', params: {}, category: 'DeFi', color: '#F77B2F', parentChain: 'Solana' },
  { id: 'mngo', name: 'Mango', symbol: 'MNGO', generator: 'solana', params: {}, category: 'DeFi', color: '#F2C94C', parentChain: 'Solana' },
  { id: 'hxro', name: 'Hxro', symbol: 'HXRO', generator: 'solana', params: {}, category: 'DeFi', color: '#1A1A2E', parentChain: 'Solana' },
  { id: 'kin', name: 'Kin', symbol: 'KIN', generator: 'solana', params: {}, category: 'Infrastructure', color: '#6F41E8', parentChain: 'Solana' },
  { id: 'sol_usdc', name: 'USDC (Solana)', symbol: 'USDCSOL', generator: 'solana', params: {}, category: 'Stablecoin', color: '#2775CA', parentChain: 'Solana' },
  { id: 'sol_usdt', name: 'USDT (Solana)', symbol: 'USDTSOL', generator: 'solana', params: {}, category: 'Stablecoin', color: '#26A17B', parentChain: 'Solana' },

  // ── More Tron ecosystem ──
  { id: 'btt', name: 'BitTorrent', symbol: 'BTT', generator: 'tron', params: {}, category: 'Infrastructure', color: '#000000', parentChain: 'Tron' },
  { id: 'win', name: 'WINkLink', symbol: 'WIN', generator: 'tron', params: {}, category: 'DeFi', color: '#000000', parentChain: 'Tron' },
  { id: 'jst', name: 'JUST', symbol: 'JST', generator: 'tron', params: {}, category: 'DeFi', color: '#B01100', parentChain: 'Tron' },
  { id: 'sun', name: 'SUN', symbol: 'SUN', generator: 'tron', params: {}, category: 'DeFi', color: '#FFD93D', parentChain: 'Tron' },

  // ══════════════════════════════════════════════════════════════════
  // 150 MORE TOKENS
  // ══════════════════════════════════════════════════════════════════

  // ── DeFi Tokens ──
  { id: 'inch_bsc', name: '1inch (BSC)', symbol: '1INCHBSC', generator: 'evm', params: {}, category: 'DeFi', color: '#94A6C3', parentChain: 'Ethereum' },
  { id: 'frxeth', name: 'Frax Ether', symbol: 'frxETH', generator: 'evm', params: {}, category: 'DeFi', color: '#000000', parentChain: 'Ethereum' },
  { id: 'sfrxeth', name: 'Staked frxETH', symbol: 'sfrxETH', generator: 'evm', params: {}, category: 'DeFi', color: '#000000', parentChain: 'Ethereum' },
  { id: 'ezeth', name: 'Renzo ezETH', symbol: 'ezETH', generator: 'evm', params: {}, category: 'DeFi', color: '#14F195', parentChain: 'Ethereum' },
  { id: 'weeth', name: 'Ether.fi weETH', symbol: 'weETH', generator: 'evm', params: {}, category: 'DeFi', color: '#7C3AED', parentChain: 'Ethereum' },
  { id: 'sweth', name: 'Swell ETH', symbol: 'swETH', generator: 'evm', params: {}, category: 'DeFi', color: '#3A70F0', parentChain: 'Ethereum' },
  { id: 'oseth', name: 'StakeWise osETH', symbol: 'osETH', generator: 'evm', params: {}, category: 'DeFi', color: '#2DD4BF', parentChain: 'Ethereum' },
  { id: 'pxeth', name: 'Dinero pxETH', symbol: 'pxETH', generator: 'evm', params: {}, category: 'DeFi', color: '#4338CA', parentChain: 'Ethereum' },
  { id: 'eeth', name: 'Ether.fi eETH', symbol: 'eETH', generator: 'evm', params: {}, category: 'DeFi', color: '#7C3AED', parentChain: 'Ethereum' },
  { id: 'inst', name: 'Instadapp', symbol: 'INST', generator: 'evm', params: {}, category: 'DeFi', color: '#3F75FF', parentChain: 'Ethereum' },
  { id: 'perp', name: 'Perpetual Protocol', symbol: 'PERP', generator: 'evm', params: {}, category: 'DeFi', color: '#3CEAB0', parentChain: 'Ethereum' },
  { id: 'badger', name: 'Badger DAO', symbol: 'BADGER', generator: 'evm', params: {}, category: 'DeFi', color: '#F2A52B', parentChain: 'Ethereum' },
  { id: 'alcx', name: 'Alchemix', symbol: 'ALCX', generator: 'evm', params: {}, category: 'DeFi', color: '#F5C09A', parentChain: 'Ethereum' },
  { id: 'fxs', name: 'Frax Share', symbol: 'FXS', generator: 'evm', params: {}, category: 'DeFi', color: '#000000', parentChain: 'Ethereum' },
  { id: 'mav', name: 'Maverick', symbol: 'MAV', generator: 'evm', params: {}, category: 'DeFi', color: '#5B46F6', parentChain: 'Ethereum' },
  { id: 'cetus', name: 'Cetus', symbol: 'CETUS', generator: 'solana', params: {}, category: 'DeFi', color: '#2191FB', parentChain: 'Solana' },
  { id: 'scallop', name: 'Scallop', symbol: 'SCA', generator: 'solana', params: {}, category: 'DeFi', color: '#0EA5E9', parentChain: 'Solana' },

  // ── Infrastructure Tokens ──
  { id: 'alt', name: 'AltLayer', symbol: 'ALT', generator: 'evm', params: {}, category: 'Infrastructure', color: '#000000', parentChain: 'Ethereum' },
  { id: 'tao', name: 'Bittensor', symbol: 'TAO', generator: 'evm', params: {}, category: 'Infrastructure', color: '#252525', parentChain: 'Ethereum' },
  { id: 'agio', name: 'Agora', symbol: 'AGORA', generator: 'evm', params: {}, category: 'Infrastructure', color: '#000000', parentChain: 'Ethereum' },
  { id: 'paal', name: 'PAAL AI', symbol: 'PAAL', generator: 'evm', params: {}, category: 'Infrastructure', color: '#06B6D4', parentChain: 'Ethereum' },
  { id: 'ait2', name: 'Artificial Liquid Intelligence', symbol: 'ALI', generator: 'evm', params: {}, category: 'Infrastructure', color: '#0D0D0D', parentChain: 'Ethereum' },
  { id: 'olas', name: 'Autonolas', symbol: 'OLAS', generator: 'evm', params: {}, category: 'Infrastructure', color: '#6B21A8', parentChain: 'Ethereum' },
  { id: 'rvst', name: 'Revest Finance', symbol: 'RVST', generator: 'evm', params: {}, category: 'Infrastructure', color: '#36A7E7', parentChain: 'Ethereum' },
  { id: 'aethir', name: 'Aethir', symbol: 'ATH', generator: 'evm', params: {}, category: 'Infrastructure', color: '#3B82F6', parentChain: 'Ethereum' },
  { id: 'arkm', name: 'Arkham', symbol: 'ARKM', generator: 'evm', params: {}, category: 'Infrastructure', color: '#000000', parentChain: 'Ethereum' },
  { id: 'ngl', name: 'Entangle', symbol: 'NGL', generator: 'evm', params: {}, category: 'Infrastructure', color: '#8B5CF6', parentChain: 'Ethereum' },
  { id: 'dusk', name: 'Dusk', symbol: 'DUSK', generator: 'evm', params: {}, category: 'Infrastructure', color: '#19191F', parentChain: 'Ethereum' },
  { id: 'rndr_arb', name: 'Render (ARB)', symbol: 'RNDR2', generator: 'evm', params: {}, category: 'Infrastructure', color: '#1E1E1E', parentChain: 'Ethereum' },
  { id: 't', name: 'Threshold', symbol: 'T', generator: 'evm', params: {}, category: 'Infrastructure', color: '#7C3AED', parentChain: 'Ethereum' },
  { id: 'ctk', name: 'Shentu', symbol: 'CTK', generator: 'evm', params: {}, category: 'Infrastructure', color: '#FFC107', parentChain: 'Ethereum' },

  // ── Meme Tokens ──
  { id: 'caw', name: 'A Hunters Dream', symbol: 'CAW', generator: 'evm', params: {}, category: 'Memecoin', color: '#000000', parentChain: 'Ethereum' },
  { id: 'tsuka', name: 'Dejitaru Tsuka', symbol: 'TSUKA', generator: 'evm', params: {}, category: 'Memecoin', color: '#BF360C', parentChain: 'Ethereum' },
  { id: 'cult', name: 'Cult DAO', symbol: 'CULT', generator: 'evm', params: {}, category: 'Memecoin', color: '#000000', parentChain: 'Ethereum' },
  { id: 'elon', name: 'Dogelon Mars', symbol: 'ELON', generator: 'evm', params: {}, category: 'Memecoin', color: '#FF6F61', parentChain: 'Ethereum' },
  { id: 'kishu', name: 'Kishu Inu', symbol: 'KISHU', generator: 'evm', params: {}, category: 'Memecoin', color: '#F4B542', parentChain: 'Ethereum' },
  { id: 'mog', name: 'Mog Coin', symbol: 'MOG', generator: 'evm', params: {}, category: 'Memecoin', color: '#7C3AED', parentChain: 'Ethereum' },
  { id: 'andy', name: 'Andy', symbol: 'ANDY', generator: 'evm', params: {}, category: 'Memecoin', color: '#FFA726', parentChain: 'Ethereum' },
  { id: 'ponke', name: 'Ponke', symbol: 'PONKE', generator: 'solana', params: {}, category: 'Memecoin', color: '#A0522D', parentChain: 'Solana' },
  { id: 'wen', name: 'WEN', symbol: 'WEN', generator: 'solana', params: {}, category: 'Memecoin', color: '#FF6347', parentChain: 'Solana' },
  { id: 'slerf', name: 'SLERF', symbol: 'SLERF', generator: 'solana', params: {}, category: 'Memecoin', color: '#8B4513', parentChain: 'Solana' },
  { id: 'boden', name: 'Jeo Boden', symbol: 'BODEN', generator: 'solana', params: {}, category: 'Memecoin', color: '#1E40AF', parentChain: 'Solana' },
  { id: 'retardio', name: 'Retardio', symbol: 'RETARDIO', generator: 'solana', params: {}, category: 'Memecoin', color: '#DC2626', parentChain: 'Solana' },
  { id: 'jeo', name: 'Jeo', symbol: 'JEO', generator: 'solana', params: {}, category: 'Memecoin', color: '#3B82F6', parentChain: 'Solana' },
  { id: 'barsik', name: 'Barsik', symbol: 'BARSIK', generator: 'solana', params: {}, category: 'Memecoin', color: '#FB923C', parentChain: 'Solana' },
  { id: 'doggo', name: 'DOGGO', symbol: 'DOGGO', generator: 'solana', params: {}, category: 'Memecoin', color: '#EAB308', parentChain: 'Solana' },
  { id: 'snek', name: 'SNEK', symbol: 'SNEK', generator: 'evm', params: {}, category: 'Memecoin', color: '#4ADE80', parentChain: 'Ethereum' },
  { id: 'pork', name: 'PepeFork', symbol: 'PORK', generator: 'evm', params: {}, category: 'Memecoin', color: '#15803D', parentChain: 'Ethereum' },
  { id: 'dino', name: 'DinoLFG', symbol: 'DINO', generator: 'solana', params: {}, category: 'Memecoin', color: '#22C55E', parentChain: 'Solana' },
  { id: 'chillguy', name: 'Just a chill guy', symbol: 'CHILLGUY', generator: 'solana', params: {}, category: 'Memecoin', color: '#60A5FA', parentChain: 'Solana' },
  { id: 'pengu', name: 'Pudgy Penguins', symbol: 'PENGU', generator: 'solana', params: {}, category: 'Memecoin', color: '#0EA5E9', parentChain: 'Solana' },
  { id: 'vine', name: 'Vine', symbol: 'VINE', generator: 'solana', params: {}, category: 'Memecoin', color: '#00BFA5', parentChain: 'Solana' },
  { id: 'melania', name: 'MELANIA', symbol: 'MELANIA', generator: 'solana', params: {}, category: 'Memecoin', color: '#EC4899', parentChain: 'Solana' },
  { id: 'giga', name: 'Giga Chad', symbol: 'GIGA', generator: 'solana', params: {}, category: 'Memecoin', color: '#92400E', parentChain: 'Solana' },

  // ── More Gaming Tokens ──
  { id: 'pyr', name: 'Vulcan Forged', symbol: 'PYR', generator: 'evm', params: {}, category: 'Gaming', color: '#FF6B35', parentChain: 'Ethereum' },
  { id: 'waxp', name: 'WAX', symbol: 'WAXP', generator: 'evm', params: {}, category: 'Gaming', color: '#F89022', parentChain: 'Ethereum' },
  { id: 'rfox', name: 'RedFOX Labs', symbol: 'RFOX', generator: 'evm', params: {}, category: 'Gaming', color: '#FF0000', parentChain: 'Ethereum' },
  { id: 'loka', name: 'League of Kingdoms', symbol: 'LOKA', generator: 'evm', params: {}, category: 'Gaming', color: '#C98A09', parentChain: 'Ethereum' },
  { id: 'ghst', name: 'Aavegotchi', symbol: 'GHST', generator: 'evm', params: {}, category: 'Gaming', color: '#FA34F3', parentChain: 'Ethereum' },
  { id: 'rare', name: 'SuperRare', symbol: 'RARE', generator: 'evm', params: {}, category: 'Gaming', color: '#000000', parentChain: 'Ethereum' },
  { id: 'alice', name: 'My Neighbor Alice', symbol: 'ALICE', generator: 'evm', params: {}, category: 'Gaming', color: '#EB6083', parentChain: 'Ethereum' },
  { id: 'tlm', name: 'Alien Worlds', symbol: 'TLM', generator: 'evm', params: {}, category: 'Gaming', color: '#7046BC', parentChain: 'Ethereum' },
  { id: 'dpet', name: 'My DeFi Pet', symbol: 'DPET', generator: 'evm', params: {}, category: 'Gaming', color: '#F5B841', parentChain: 'Ethereum' },
  { id: 'sfund', name: 'Seedify', symbol: 'SFUND', generator: 'evm', params: {}, category: 'Gaming', color: '#00C853', parentChain: 'Ethereum' },
  { id: 'mc', name: 'Merit Circle', symbol: 'MC', generator: 'evm', params: {}, category: 'Gaming', color: '#FFE81F', parentChain: 'Ethereum' },
  { id: 'mbox', name: 'MOBOX', symbol: 'MBOX', generator: 'evm', params: {}, category: 'Gaming', color: '#1688F0', parentChain: 'Ethereum' },
  { id: 'dep', name: 'DEAPcoin', symbol: 'DEP', generator: 'evm', params: {}, category: 'Gaming', color: '#00B2FF', parentChain: 'Ethereum' },
  { id: 'revv', name: 'REVV', symbol: 'REVV', generator: 'evm', params: {}, category: 'Gaming', color: '#FF3B3B', parentChain: 'Ethereum' },
  { id: 'aury', name: 'Aurory', symbol: 'AURY', generator: 'solana', params: {}, category: 'Gaming', color: '#5B25C9', parentChain: 'Solana' },

  // ── Additional ERC-20 ──
  { id: 'snt', name: 'Status', symbol: 'SNT', generator: 'evm', params: {}, category: 'Infrastructure', color: '#5B6DEE', parentChain: 'Ethereum' },
  { id: 'ach', name: 'Alchemy Pay', symbol: 'ACH', generator: 'evm', params: {}, category: 'Infrastructure', color: '#5658DD', parentChain: 'Ethereum' },
  { id: 'audio', name: 'Audius', symbol: 'AUDIO', generator: 'evm', params: {}, category: 'Infrastructure', color: '#9400D3', parentChain: 'Ethereum' },
  { id: 'ctsi', name: 'Cartesi', symbol: 'CTSI', generator: 'evm', params: {}, category: 'Infrastructure', color: '#1A1B1F', parentChain: 'Ethereum' },
  { id: 'jasmy', name: 'JasmyCoin', symbol: 'JASMY', generator: 'evm', params: {}, category: 'Infrastructure', color: '#F7931E', parentChain: 'Ethereum' },
  { id: 'celr', name: 'Celer Network', symbol: 'CELR', generator: 'evm', params: {}, category: 'Infrastructure', color: '#000000', parentChain: 'Ethereum' },
  { id: 'pond', name: 'Marlin', symbol: 'POND', generator: 'evm', params: {}, category: 'Infrastructure', color: '#0E4FFF', parentChain: 'Ethereum' },
  { id: 'coti', name: 'COTI', symbol: 'COTI', generator: 'evm', params: {}, category: 'Infrastructure', color: '#0066FF', parentChain: 'Ethereum' },
  { id: 'dent', name: 'Dent', symbol: 'DENT', generator: 'evm', params: {}, category: 'Infrastructure', color: '#2CABEF', parentChain: 'Ethereum' },
  { id: 'prom', name: 'Prom', symbol: 'PROM', generator: 'evm', params: {}, category: 'Infrastructure', color: '#3E1FAC', parentChain: 'Ethereum' },
  { id: 'rsr', name: 'Reserve Rights', symbol: 'RSR', generator: 'evm', params: {}, category: 'DeFi', color: '#000000', parentChain: 'Ethereum' },
  { id: 'stg', name: 'Stargate', symbol: 'STG', generator: 'evm', params: {}, category: 'DeFi', color: '#000000', parentChain: 'Ethereum' },
  { id: 'magic_eth', name: 'Magic (ETH)', symbol: 'MAGIC2', generator: 'evm', params: {}, category: 'Gaming', color: '#DC2626', parentChain: 'Ethereum' },
  { id: 'gt', name: 'Gate Token', symbol: 'GT', generator: 'evm', params: {}, category: 'Infrastructure', color: '#2354E6', parentChain: 'Ethereum' },
  { id: 'ht2', name: 'Huobi Token', symbol: 'HT2', generator: 'evm', params: {}, category: 'Infrastructure', color: '#2DAF68', parentChain: 'Ethereum' },
  { id: 'mx', name: 'MEXC Token', symbol: 'MX', generator: 'evm', params: {}, category: 'Infrastructure', color: '#000000', parentChain: 'Ethereum' },
  { id: 'nexo', name: 'Nexo', symbol: 'NEXO', generator: 'evm', params: {}, category: 'DeFi', color: '#1E4DD8', parentChain: 'Ethereum' },
  { id: 'chz', name: 'Chiliz', symbol: 'CHZ', generator: 'evm', params: {}, category: 'Infrastructure', color: '#CD0124', parentChain: 'Ethereum' },
  { id: 'hot', name: 'Holo', symbol: 'HOT', generator: 'evm', params: {}, category: 'Infrastructure', color: '#00838F', parentChain: 'Ethereum' },
  { id: 'mpl', name: 'Maple Finance', symbol: 'MPL', generator: 'evm', params: {}, category: 'DeFi', color: '#9333EA', parentChain: 'Ethereum' },

  // ══════════════════════════════════════════════════════════════════
  // 65 MORE BLOCKCHAINS
  // ══════════════════════════════════════════════════════════════════

  // ── EVM L2/L3 Chains ──
  { id: 'gravity', name: 'Gravity', symbol: 'G', generator: 'evm', params: {}, category: 'EVM Chain', color: '#6366F1', parentChain: 'EVM' },
  { id: 'snaxchain', name: 'Snax Chain', symbol: 'SNAX', generator: 'evm', params: {}, category: 'EVM Chain', color: '#2563EB', parentChain: 'EVM' },
  { id: 'kroma', name: 'Kroma', symbol: 'KRO', generator: 'evm', params: {}, category: 'EVM Chain', color: '#48BB78', parentChain: 'EVM' },
  { id: 'shape', name: 'Shape', symbol: 'SHAPE', generator: 'evm', params: {}, category: 'EVM Chain', color: '#000000', parentChain: 'EVM' },
  { id: 'swan', name: 'Swan Chain', symbol: 'SWAN', generator: 'evm', params: {}, category: 'EVM Chain', color: '#2DD4BF', parentChain: 'EVM' },
  { id: 'metal', name: 'Metal L2', symbol: 'MTL', generator: 'evm', params: {}, category: 'EVM Chain', color: '#7C3AED', parentChain: 'EVM' },
  { id: 'sanko', name: 'Sanko', symbol: 'DMT', generator: 'evm', params: {}, category: 'EVM Chain', color: '#FF5733', parentChain: 'EVM' },
  { id: 'polynomial', name: 'Polynomial', symbol: 'POLY', generator: 'evm', params: {}, category: 'EVM Chain', color: '#8B5CF6', parentChain: 'EVM' },
  { id: 'superposition', name: 'Superposition', symbol: 'SUPER2', generator: 'evm', params: {}, category: 'EVM Chain', color: '#F43F5E', parentChain: 'EVM' },
  { id: 'derive', name: 'Derive', symbol: 'DRV', generator: 'evm', params: {}, category: 'EVM Chain', color: '#06B6D4', parentChain: 'EVM' },
  { id: 'xlayer', name: 'X Layer', symbol: 'XLAYER', generator: 'evm', params: {}, category: 'EVM Chain', color: '#000000', parentChain: 'EVM' },
  { id: 'immutable_zk', name: 'Immutable zkEVM', symbol: 'IMXZK', generator: 'evm', params: {}, category: 'EVM Chain', color: '#00C3FF', parentChain: 'EVM' },
  { id: 'proof_of_play', name: 'Proof of Play', symbol: 'POP', generator: 'evm', params: {}, category: 'EVM Chain', color: '#FF6B00', parentChain: 'EVM' },
  { id: 'fraxtal2', name: 'Fraxtal', symbol: 'FRAX2', generator: 'evm', params: {}, category: 'EVM Chain', color: '#000000', parentChain: 'EVM' },
  { id: 'treasure_chain', name: 'Treasure Chain', symbol: 'MAGIC3', generator: 'evm', params: {}, category: 'EVM Chain', color: '#DC2626', parentChain: 'EVM' },

  // ── Cosmos Chains ──
  { id: 'berachain', name: 'Berachain', symbol: 'BERA', generator: 'cosmos', params: { prefix: 'bera' }, category: 'Cosmos', color: '#7C2D12' },
  { id: 'zetachain_c', name: 'ZetaChain (Cosmos)', symbol: 'ZETA2', generator: 'cosmos', params: { prefix: 'zeta' }, category: 'Cosmos', color: '#00BC8D' },
  { id: 'noble', name: 'Noble', symbol: 'USDN', generator: 'cosmos', params: { prefix: 'noble' }, category: 'Cosmos', color: '#F5F5F5' },
  { id: 'carbon', name: 'Carbon', symbol: 'SWTH', generator: 'cosmos', params: { prefix: 'swth' }, category: 'Cosmos', color: '#05C992' },
  { id: 'terra2', name: 'Terra 2.0', symbol: 'LUNA', generator: 'cosmos', params: { prefix: 'terra' }, category: 'Cosmos', color: '#172852' },
  { id: 'terrac', name: 'Terra Classic', symbol: 'LUNC', generator: 'cosmos', params: { prefix: 'terra' }, category: 'Cosmos', color: '#FFD83D' },
  { id: 'cronos_pos', name: 'Cronos POS', symbol: 'CRO2', generator: 'cosmos', params: { prefix: 'cro' }, category: 'Cosmos', color: '#002D74' },
  { id: 'sif', name: 'Sifchain', symbol: 'EROWAN', generator: 'cosmos', params: { prefix: 'sif' }, category: 'Cosmos', color: '#C5A86C' },
  { id: 'chihuahua', name: 'Chihuahua', symbol: 'HUAHUA', generator: 'cosmos', params: { prefix: 'chihuahua' }, category: 'Cosmos', color: '#F5A623' },
  { id: 'likecoin', name: 'LikeCoin', symbol: 'LIKE', generator: 'cosmos', params: { prefix: 'like' }, category: 'Cosmos', color: '#28646E' },

  // ── Polkadot/Substrate ──
  { id: 'origintrail', name: 'OriginTrail', symbol: 'TRAC', generator: 'polkadot', params: { networkId: 101 }, category: 'Layer 1', color: '#1B1464' },
  { id: 'clover', name: 'Clover', symbol: 'CLV', generator: 'polkadot', params: { networkId: 128 }, category: 'Layer 1', color: '#00A86B' },
  { id: 'darwinia', name: 'Darwinia', symbol: 'RING', generator: 'polkadot', params: { networkId: 18 }, category: 'Layer 1', color: '#FF0083' },
  { id: 'crust', name: 'Crust', symbol: 'CRU', generator: 'polkadot', params: { networkId: 66 }, category: 'Layer 1', color: '#FA5C4F' },
  { id: 'ajuna', name: 'Ajuna', symbol: 'AJUN', generator: 'polkadot', params: { networkId: 1328 }, category: 'Layer 1', color: '#F97316' },

  // ── Bitcoin Forks ──
  { id: 'emc2', name: 'Einsteinium', symbol: 'EMC2', generator: 'btc-legacy', params: { versionByte: 0x21, wifByte: 0xa1 }, category: 'Bitcoin Fork', color: '#423768' },
  { id: 'xpm', name: 'Primecoin', symbol: 'XPM', generator: 'btc-legacy', params: { versionByte: 0x17, wifByte: 0x97 }, category: 'Bitcoin Fork', color: '#CDC3A7' },
  { id: 'blk', name: 'BlackCoin', symbol: 'BLK', generator: 'btc-legacy', params: { versionByte: 0x19, wifByte: 0x99 }, category: 'Bitcoin Fork', color: '#333333' },
  { id: 'game', name: 'GameCredits', symbol: 'GAME', generator: 'btc-legacy', params: { versionByte: 0x26, wifByte: 0xa6 }, category: 'Bitcoin Fork', color: '#2D9CDB' },
  { id: 'nyc', name: 'NewYorkCoin', symbol: 'NYC', generator: 'btc-legacy', params: { versionByte: 0x3c, wifByte: 0xbc }, category: 'Bitcoin Fork', color: '#4A90D9' },
  { id: 'rdd', name: 'ReddCoin', symbol: 'RDD', generator: 'btc-legacy', params: { versionByte: 0x3d, wifByte: 0xbd }, category: 'Bitcoin Fork', color: '#E30613' },
  { id: 'pot', name: 'PotCoin', symbol: 'POT', generator: 'btc-legacy', params: { versionByte: 0x37, wifByte: 0xb7 }, category: 'Bitcoin Fork', color: '#105B2F' },
  { id: 'xdn', name: 'DigitalNote', symbol: 'XDN', generator: 'btc-legacy', params: { versionByte: 0x5a, wifByte: 0x80 }, category: 'Bitcoin Fork', color: '#4AB5E2' },
  { id: 'cloak', name: 'CloakCoin', symbol: 'CLOAK', generator: 'btc-legacy', params: { versionByte: 0x1b, wifByte: 0x9b }, category: 'Bitcoin Fork', color: '#FF0000' },
  { id: 'bitcore', name: 'Bitcore', symbol: 'BTX', generator: 'btc-legacy', params: { versionByte: 0x03, wifByte: 0x80 }, category: 'Bitcoin Fork', color: '#F5A623' },

  // ── Standalone L1s ──
  { id: 'ckb2', name: 'Nervos CKB', symbol: 'CKB2', generator: 'evm', params: {}, category: 'Layer 1', color: '#3CC68A' },
  { id: 'qtum', name: 'Qtum', symbol: 'QTUM', generator: 'btc-legacy', params: { versionByte: 0x3a, wifByte: 0x80 }, category: 'Layer 1', color: '#2E9AD0' },
  { id: 'wan', name: 'Wanchain', symbol: 'WAN', generator: 'evm', params: {}, category: 'Layer 1', color: '#136AAD' },
  { id: 'btt2', name: 'BitTorrent Chain', symbol: 'BTT2', generator: 'evm', params: {}, category: 'Layer 1', color: '#000000' },
  { id: 'ela', name: 'Elastos', symbol: 'ELA', generator: 'evm', params: {}, category: 'Layer 1', color: '#3FBADF' },
  { id: 'rsk', name: 'RSK', symbol: 'RBTC2', generator: 'evm', params: {}, category: 'Layer 1', color: '#00A651' },
  { id: 'velas', name: 'Velas', symbol: 'VLX', generator: 'evm', params: {}, category: 'Layer 1', color: '#0037C6' },
  { id: 'syscoin_nevm', name: 'Syscoin NEVM', symbol: 'SYS2', generator: 'evm', params: {}, category: 'Layer 1', color: '#0082C6' },
  { id: 'conflux', name: 'Conflux', symbol: 'CFX', generator: 'evm', params: {}, category: 'Layer 1', color: '#1C1C1C' },
  { id: 'songbird', name: 'Songbird', symbol: 'SGB', generator: 'evm', params: {}, category: 'Layer 1', color: '#000063' },
  { id: 'shimmer', name: 'Shimmer', symbol: 'SMR', generator: 'evm', params: {}, category: 'Layer 1', color: '#25DFCA' },
  { id: 'aleph', name: 'Aleph Zero', symbol: 'AZERO', generator: 'polkadot', params: { networkId: 42 }, category: 'Layer 1', color: '#00EAC7' },
  { id: 'concordium', name: 'Concordium', symbol: 'CCD', generator: 'near', params: {}, category: 'Layer 1', color: '#18223A' },
  { id: 'radix', name: 'Radix', symbol: 'XRD', generator: 'evm', params: {}, category: 'Layer 1', color: '#052CC0' },
  { id: 'verus', name: 'Verus', symbol: 'VRSC', generator: 'btc-legacy', params: { versionByte: 0x3c, wifByte: 0xbc }, category: 'Layer 1', color: '#3165D4' },
];
